services:
  database:
    image: pgvector/pgvector:pg16
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 10

  backend:
    build:
      context: .
    env_file:
    - .env.production
    environment:
      ENVIRONMENT: production
      FRONTEND_BASE_URL: ${FRONTEND_BASE_URL}
      AWS_REGION: ${AWS_REGION}
      SES_SENDER_EMAIL: ${SES_SENDER_EMAIL}
      AWS_S3_BUCKET: ${AWS_S3_BUCKET}
      AWS_S3_REGION: ${AWS_S3_REGION}
      AWS_CLOUDFRONT_DOMAIN: ${AWS_CLOUDFRONT_DOMAIN}
    volumes:
      - /app/.venv
      - /app/__pycache__
    command: ["sh", "./start.sh"]
    ports:
      - "8000:8000"
    depends_on:
      database:
        condition: service_healthy

volumes:
  postgres_data:
