"""add tourism data fields

Revision ID: 50eec33b9c88
Revises: 3963a63d3998
Create Date: 2026-08-15 09:41:15.505380

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "50eec33b9c88"
down_revision: Union[str, Sequence[str], None] = "3963a63d3998"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "attractions", sa.Column("name", sa.String(length=255), nullable=False)
    )
    op.add_column("attractions", sa.Column("description", sa.Text(), nullable=True))
    op.add_column(
        "attractions",
        sa.Column("rating", sa.Numeric(precision=2, scale=1), nullable=True),
    )
    op.add_column("hotels", sa.Column("name", sa.String(length=255), nullable=False))
    op.add_column("hotels", sa.Column("description", sa.Text(), nullable=True))
    op.add_column("hotels", sa.Column("location", sa.String(length=255), nullable=True))
    op.add_column(
        "local_events", sa.Column("name", sa.String(length=255), nullable=False)
    )
    op.add_column(
        "local_events", sa.Column("category", sa.String(length=100), nullable=False)
    )
    op.add_column(
        "local_events",
        sa.Column("entry_fee", sa.Numeric(precision=10, scale=2), nullable=False),
    )
    op.add_column(
        "restaurants", sa.Column("name", sa.String(length=255), nullable=False)
    )
    op.add_column(
        "restaurants",
        sa.Column(
            "operating_hours", postgresql.JSONB(astext_type=sa.Text()), nullable=True
        ),
    )
    op.add_column(
        "restaurants",
        sa.Column("rating", sa.Numeric(precision=2, scale=1), nullable=True),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("restaurants", "rating")
    op.drop_column("restaurants", "operating_hours")
    op.drop_column("restaurants", "name")
    op.drop_column("local_events", "entry_fee")
    op.drop_column("local_events", "category")
    op.drop_column("local_events", "name")
    op.drop_column("hotels", "location")
    op.drop_column("hotels", "description")
    op.drop_column("hotels", "name")
    op.drop_column("attractions", "rating")
    op.drop_column("attractions", "description")
    op.drop_column("attractions", "name")
    # ### end Alembic commands ###
