from app.core.seed_data._helpers import hours

DESTINATION = {
    "name": "Anuradhapura",
    "description": "Sri Lanka's first ancient capital, a UNESCO site of vast stupas, monasteries and sacred Bo tree.",
    "country": "Sri Lanka",
    "region": "North Central Province",
    "latitude": 8.3114,
    "longitude": 80.4037,
    "is_active": True,
    "attractions": [
        {
            "name": "Sri Maha Bodhi",
            "description": "Sacred fig tree grown from a cutting of the tree under which the Buddha was enlightened.",
            "latitude": 8.345,
            "longitude": 80.396,
            "entry_fee": 5.00,
            "duration_hours": 1.5,
            "rating": 4.8,
            "opening_hours": hours("05:00-20:00"),
        },
        {
            "name": "Ruwanwelisaya",
            "description": "Gleaming white stupa and one of the most revered Buddhist monuments.",
            "latitude": 8.3504,
            "longitude": 80.3958,
            "entry_fee": 0.00,
            "duration_hours": 1.5,
            "rating": 4.8,
            "opening_hours": hours("05:00-20:00"),
        },
        {
            "name": "Jetavanaramaya",
            "description": "Massive brick stupa, once one of the tallest structures in the world.",
            "latitude": 8.35,
            "longitude": 80.406,
            "entry_fee": 10.00,
            "duration_hours": 2.0,
            "rating": 4.6,
            "opening_hours": hours("06:00-18:00"),
        },
        {
            "name": "Abhayagiri Monastery",
            "description": "Vast ruined monastery complex with a giant stupa and moonstones.",
            "latitude": 8.3775,
            "longitude": 80.4035,
            "entry_fee": 10.00,
            "duration_hours": 2.5,
            "rating": 4.5,
            "opening_hours": hours("06:00-18:00"),
        },
        {
            "name": "Isurumuniya Temple",
            "description": "Rock temple known for the carving of the Isurumuniya Lovers.",
            "latitude": 8.3281,
            "longitude": 80.3994,
            "entry_fee": 3.00,
            "duration_hours": 1.0,
            "rating": 4.3,
            "opening_hours": hours("07:00-18:00"),
        },
        {
            "name": "Mirisawetiya Stupa",
            "description": "Large stupa built by King Dutugemunu beside Tissa Lake.",
            "latitude": 8.3305,
            "longitude": 80.389,
            "entry_fee": 0.00,
            "duration_hours": 1.0,
            "rating": 4.4,
            "opening_hours": hours("06:00-18:00"),
        },
        {
            "name": "Lovamahapaya",
            "description": "Ruins of the Brazen Palace with rows of ancient stone pillars.",
            "latitude": 8.3485,
            "longitude": 80.3975,
            "entry_fee": 5.00,
            "duration_hours": 1.0,
            "rating": 4.1,
            "opening_hours": hours("07:00-18:00"),
        },
        {
            "name": "Kuttam Pokuna",
            "description": "Twin ponds with elegant stonework, once royal bathing tanks.",
            "latitude": 8.3735,
            "longitude": 80.407,
            "entry_fee": 5.00,
            "duration_hours": 1.0,
            "rating": 4.2,
            "opening_hours": hours("07:00-18:00"),
        },
        {
            "name": "Mihintale",
            "description": "Sacred mountain where Buddhism arrived in Sri Lanka, reached by a long stone stairway.",
            "latitude": 8.351,
            "longitude": 80.508,
            "entry_fee": 10.00,
            "duration_hours": 3.0,
            "rating": 4.7,
            "opening_hours": hours("05:30-18:00"),
        },
        {
            "name": "Tissa Wewa",
            "description": "Ancient reservoir with a peaceful walkway and sunset views.",
            "latitude": 8.322,
            "longitude": 80.404,
            "entry_fee": 0.00,
            "duration_hours": 1.5,
            "rating": 4.3,
            "opening_hours": hours("06:00-19:00"),
        },
    ],
    "hotels": [
        {
            "name": "Anuradhapura Budget Stay",
            "description": "Clean, simple rooms a short ride from the sacred city.",
            "latitude": 8.315,
            "longitude": 80.41,
            "price_per_night": 32.00,
            "facilities": ["WiFi", "Breakfast", "Fan"],
            "rating": 4.0,
        },
        {
            "name": "Sacred City Hotel",
            "description": "Mid-range hotel with a garden restaurant near the Bodhi tree.",
            "latitude": 8.34,
            "longitude": 80.401,
            "price_per_night": 90.00,
            "facilities": ["WiFi", "Restaurant", "Breakfast", "Parking"],
            "rating": 4.3,
        },
        {
            "name": "Tissa Lake Resort",
            "description": "Upscale lakeside resort with pool and spa.",
            "latitude": 8.319,
            "longitude": 80.409,
            "price_per_night": 150.00,
            "facilities": ["WiFi", "Pool", "Spa", "Restaurant"],
            "rating": 4.6,
        },
    ],
    "restaurants": [
        {
            "name": "Sacred City Rice and Curry",
            "description": "Traditional rice and curry for pilgrims and visitors, open until late afternoon.",
            "latitude": 8.342,
            "longitude": 80.399,
            "cuisine_type": "Local Sri Lankan",
            "avg_meal_cost": 7.00,
            "rating": 4.4,
            "operating_hours": hours("07:30-16:30"),
        },
        {
            "name": "Lakeside Curry House",
            "description": "Lake-view restaurant serving Sri Lankan dishes and fresh fish.",
            "latitude": 8.32,
            "longitude": 80.406,
            "cuisine_type": "Local Sri Lankan",
            "avg_meal_cost": 12.00,
            "rating": 4.3,
            "operating_hours": hours("11:00-22:00"),
        },
        {
            "name": "Anuradhapura Spice Garden",
            "description": "North Indian curries and tandoor dishes.",
            "latitude": 8.313,
            "longitude": 80.408,
            "cuisine_type": "Indian",
            "avg_meal_cost": 11.00,
            "rating": 4.2,
            "operating_hours": hours("11:00-22:30"),
        },
        {
            "name": "Lotus Pond Chinese",
            "description": "Chinese restaurant with a quiet courtyard.",
            "latitude": 8.316,
            "longitude": 80.402,
            "cuisine_type": "Chinese",
            "avg_meal_cost": 12.00,
            "rating": 4.0,
            "operating_hours": hours("11:30-22:00"),
        },
        {
            "name": "Bodhi Bistro",
            "description": "Western-style cafe-restaurant with grills and desserts.",
            "latitude": 8.338,
            "longitude": 80.403,
            "cuisine_type": "Western",
            "avg_meal_cost": 16.00,
            "rating": 4.2,
            "operating_hours": hours("12:00-23:00"),
        },
    ],
    "events": [
        {
            "name": "Poson Poya Festival",
            "description": "Pilgrim festival at Mihintale and Anuradhapura with processions and devotional singing.",
            "latitude": 8.348,
            "longitude": 80.4,
            "entry_fee": 0.00,
            "rating": 4.7,
            "days_ahead": 50,
            "duration_days": 1,
            "start_time": "17:00",
            "end_time": "22:00",
        },
        {
            "name": "Anuradhapura Heritage Walk Festival",
            "description": "Guided walks and talks across the ancient city with traditional music.",
            "latitude": 8.334,
            "longitude": 80.407,
            "entry_fee": 6.00,
            "rating": 4.3,
            "days_ahead": 130,
            "duration_days": 1,
            "start_time": "09:00",
            "end_time": "16:00",
        },
    ],
}
