from app.core.seed_data._helpers import hours

DESTINATION = {
    "name": "Arugam Bay",
    "description": "Laid-back east-coast surf town with a famous point break, lagoons and nearby wildlife parks.",
    "country": "Sri Lanka",
    "region": "Eastern Province",
    "latitude": 6.84,
    "longitude": 81.835,
    "is_active": True,
    "attractions": [
        {
            "name": "Arugam Bay Beach",
            "description": "Wide bay with golden sand, beach cafes and sunrise views.",
            "latitude": 6.841,
            "longitude": 81.838,
            "entry_fee": 0.00,
            "duration_hours": 3.0,
            "rating": 4.6,
            "opening_hours": hours("06:00-18:00"),
        },
        {
            "name": "Main Point Surf Lesson",
            "description": "Beginner and intermediate surf lessons on the main point break.",
            "latitude": 6.835,
            "longitude": 81.842,
            "entry_fee": 20.00,
            "duration_hours": 2.0,
            "rating": 4.7,
            "opening_hours": hours("06:00-17:00"),
        },
        {
            "name": "Elephant Rock",
            "description": "Rocky headland shaped like an elephant, good for sunset views.",
            "latitude": 6.821,
            "longitude": 81.847,
            "entry_fee": 0.00,
            "duration_hours": 1.5,
            "rating": 4.2,
            "opening_hours": hours("06:00-18:00"),
        },
        {
            "name": "Pottuvil Lagoon Safari",
            "description": "Boat safari through mangroves to spot crocodiles and birdlife.",
            "latitude": 6.872,
            "longitude": 81.833,
            "entry_fee": 20.00,
            "duration_hours": 2.5,
            "rating": 4.5,
            "opening_hours": hours("06:00-17:00"),
        },
        {
            "name": "Muhudu Maha Viharaya",
            "description": "Ancient seaside temple with a sacred stupa and sea views.",
            "latitude": 6.876,
            "longitude": 81.847,
            "entry_fee": 0.00,
            "duration_hours": 1.0,
            "rating": 4.3,
            "opening_hours": hours("06:00-18:00"),
        },
        {
            "name": "Peanut Farm Beach",
            "description": "Quiet beach with gentle waves, popular with beginner surfers.",
            "latitude": 6.815,
            "longitude": 81.858,
            "entry_fee": 0.00,
            "duration_hours": 2.0,
            "rating": 4.3,
            "opening_hours": hours("06:00-18:00"),
        },
        {
            "name": "Whiskey Point Beach",
            "description": "Secluded surf spot reached by a sandy track.",
            "latitude": 6.806,
            "longitude": 81.865,
            "entry_fee": 0.00,
            "duration_hours": 2.0,
            "rating": 4.4,
            "opening_hours": hours("06:00-18:00"),
        },
        {
            "name": "Crocodile Rock",
            "description": "Coastal rock outcrop with tide pools and surf views.",
            "latitude": 6.811,
            "longitude": 81.854,
            "entry_fee": 0.00,
            "duration_hours": 1.5,
            "rating": 4.1,
            "opening_hours": hours("06:00-18:00"),
        },
        {
            "name": "Lahugala Kithulana National Park",
            "description": "Small park famous for dry-season elephant gatherings.",
            "latitude": 6.85,
            "longitude": 81.715,
            "entry_fee": 15.00,
            "duration_hours": 2.5,
            "rating": 4.4,
            "opening_hours": hours("06:00-18:00"),
        },
        {
            "name": "Magul Maha Viharaya",
            "description": "Ruined temple complex from the Ruhuna kingdom.",
            "latitude": 6.872,
            "longitude": 81.689,
            "entry_fee": 3.00,
            "duration_hours": 1.0,
            "rating": 4.1,
            "opening_hours": hours("07:00-17:00"),
        },
    ],
    "hotels": [
        {
            "name": "Surfers Rest Arugam Bay",
            "description": "Budget surf lodge steps from the main break.",
            "latitude": 6.842,
            "longitude": 81.836,
            "price_per_night": 25.00,
            "facilities": ["WiFi", "Breakfast", "Fan"],
            "rating": 4.1,
        },
        {
            "name": "Bay Palm Villas",
            "description": "Mid-range beach villas with garden courtyards.",
            "latitude": 6.838,
            "longitude": 81.839,
            "price_per_night": 80.00,
            "facilities": ["WiFi", "Restaurant", "Breakfast", "Air Conditioning"],
            "rating": 4.4,
        },
        {
            "name": "Cliffside Surf Resort",
            "description": "Upscale clifftop resort with a pool and ocean views.",
            "latitude": 6.83,
            "longitude": 81.845,
            "price_per_night": 150.00,
            "facilities": ["WiFi", "Pool", "Spa", "Restaurant", "Sea View"],
            "rating": 4.6,
        },
    ],
    "restaurants": [
        {
            "name": "Arugam Rice and Curry Hut",
            "description": "Simple local rice and curry, open for breakfast and lunch.",
            "latitude": 6.8405,
            "longitude": 81.834,
            "cuisine_type": "Local Sri Lankan",
            "avg_meal_cost": 7.00,
            "rating": 4.4,
            "operating_hours": hours("07:30-16:30"),
        },
        {
            "name": "Bay Seafood Shack",
            "description": "Evening beach grill with the day's catch and cold drinks.",
            "latitude": 6.8395,
            "longitude": 81.8375,
            "cuisine_type": "Seafood",
            "avg_meal_cost": 20.00,
            "rating": 4.6,
            "operating_hours": hours("17:00-23:00"),
        },
        {
            "name": "Surf Shack Cafe",
            "description": "Cafe with smoothie bowls, burgers and wood-fired pizza.",
            "latitude": 6.8415,
            "longitude": 81.8365,
            "cuisine_type": "Western",
            "avg_meal_cost": 13.00,
            "rating": 4.3,
            "operating_hours": hours("08:00-22:00"),
        },
        {
            "name": "Pottuvil Indian Kitchen",
            "description": "South Indian curries and vegetarian thalis.",
            "latitude": 6.8385,
            "longitude": 81.8345,
            "cuisine_type": "Indian",
            "avg_meal_cost": 9.00,
            "rating": 4.2,
            "operating_hours": hours("11:00-22:30"),
        },
        {
            "name": "East Coast Wok",
            "description": "Chinese stir-fries and noodles for surfers on a budget.",
            "latitude": 6.8425,
            "longitude": 81.8355,
            "cuisine_type": "Chinese",
            "avg_meal_cost": 10.00,
            "rating": 4.0,
            "operating_hours": hours("11:30-22:00"),
        },
    ],
    "events": [
        {
            "name": "Arugam Bay Surf Festival",
            "description": "Surf contest and beach party with local and visiting riders.",
            "latitude": 6.834,
            "longitude": 81.841,
            "entry_fee": 5.00,
            "rating": 4.6,
            "days_ahead": 85,
            "duration_days": 1,
            "start_time": "08:00",
            "end_time": "18:00",
        },
        {
            "name": "Arugam Bay Beach Bonfire Night",
            "description": "Evening bonfire with live music, fire dancers and street food.",
            "latitude": 6.843,
            "longitude": 81.839,
            "entry_fee": 6.00,
            "rating": 4.4,
            "days_ahead": 140,
            "duration_days": 1,
            "start_time": "18:00",
            "end_time": "23:00",
        },
    ],
}
