from app.core.seed_data._helpers import hours

DESTINATION = {
    "name": "Bentota",
    "description": "Resort town on the south-west coast with a golden beach, river and lagoon activities, and nearby gardens.",
    "country": "Sri Lanka",
    "region": "Southern Province",
    "latitude": 6.426,
    "longitude": 79.995,
    "is_active": True,
    "attractions": [
        {
            "name": "Bentota Beach",
            "description": "Wide golden beach with gentle surf and water sports.",
            "latitude": 6.418,
            "longitude": 79.993,
            "entry_fee": 0.00,
            "duration_hours": 3.0,
            "rating": 4.6,
            "opening_hours": hours("06:00-18:00"),
        },
        {
            "name": "Bentota Water Sports Centre",
            "description": "Jet skiing, banana boats and windsurfing on the river mouth.",
            "latitude": 6.435,
            "longitude": 80.001,
            "entry_fee": 25.00,
            "duration_hours": 2.0,
            "rating": 4.4,
            "opening_hours": hours("08:00-17:00"),
        },
        {
            "name": "Brief Garden",
            "description": "Landscaped garden created by artist Bevis Bawa with sculptures and fountains.",
            "latitude": 6.478,
            "longitude": 80.014,
            "entry_fee": 8.00,
            "duration_hours": 1.5,
            "rating": 4.4,
            "opening_hours": hours("09:00-17:00"),
        },
        {
            "name": "Lunuganga Estate",
            "description": "Country estate and gardens designed by architect Geoffrey Bawa.",
            "latitude": 6.489,
            "longitude": 80.011,
            "entry_fee": 15.00,
            "duration_hours": 1.5,
            "rating": 4.6,
            "opening_hours": hours("09:00-17:00"),
        },
        {
            "name": "Galapota Beach Temple",
            "description": "Small seaside temple with a quiet beach.",
            "latitude": 6.403,
            "longitude": 79.988,
            "entry_fee": 0.00,
            "duration_hours": 1.0,
            "rating": 4.1,
            "opening_hours": hours("06:00-18:00"),
        },
        {
            "name": "Kosgoda Turtle Hatchery",
            "description": "Conservation centre that hatches and releases sea turtles.",
            "latitude": 6.347,
            "longitude": 80.023,
            "entry_fee": 5.00,
            "duration_hours": 1.5,
            "rating": 4.2,
            "opening_hours": hours("08:00-17:00"),
        },
        {
            "name": "Kosgoda Beach",
            "description": "Quieter beach known for turtle nesting.",
            "latitude": 6.341,
            "longitude": 80.013,
            "entry_fee": 0.00,
            "duration_hours": 2.0,
            "rating": 4.3,
            "opening_hours": hours("06:00-18:00"),
        },
        {
            "name": "Madu River Boat Safari",
            "description": "Boat trip through mangroves and small islands, including a cinnamon island.",
            "latitude": 6.303,
            "longitude": 80.048,
            "entry_fee": 20.00,
            "duration_hours": 2.5,
            "rating": 4.6,
            "opening_hours": hours("08:00-17:00"),
        },
        {
            "name": "Aluthgama Craft Market",
            "description": "Market of handicrafts, wood carving and batik close to the railway.",
            "latitude": 6.431,
            "longitude": 79.999,
            "entry_fee": 0.00,
            "duration_hours": 1.5,
            "rating": 4.0,
            "opening_hours": hours("09:00-18:00"),
        },
        {
            "name": "Bentota Ayurveda Garden",
            "description": "Herbal garden with guided tours and short treatments.",
            "latitude": 6.42,
            "longitude": 80.005,
            "entry_fee": 10.00,
            "duration_hours": 2.0,
            "rating": 4.2,
            "opening_hours": hours("08:00-17:00"),
        },
    ],
    "hotels": [
        {
            "name": "Bentota Beach Hostel",
            "description": "Budget beachside guesthouse with private rooms and dorms.",
            "latitude": 6.417,
            "longitude": 79.992,
            "price_per_night": 40.00,
            "facilities": ["WiFi", "Breakfast", "Fan"],
            "rating": 4.0,
        },
        {
            "name": "River Bend Hotel",
            "description": "Mid-range hotel on the river with a pool and restaurant.",
            "latitude": 6.433,
            "longitude": 80.002,
            "price_per_night": 110.00,
            "facilities": ["WiFi", "Pool", "Restaurant", "Breakfast"],
            "rating": 4.4,
        },
        {
            "name": "Bentota Grand Resort",
            "description": "Luxury beach resort with spa, multiple restaurants and water sports.",
            "latitude": 6.412,
            "longitude": 79.99,
            "price_per_night": 230.00,
            "facilities": ["WiFi", "Pool", "Spa", "Fine Dining", "Sea View", "Gym"],
            "rating": 4.8,
        },
    ],
    "restaurants": [
        {
            "name": "Bentota Beach Grill",
            "description": "Beachfront restaurant with fresh seafood and cocktails.",
            "latitude": 6.4175,
            "longitude": 79.9935,
            "cuisine_type": "Seafood",
            "avg_meal_cost": 20.00,
            "rating": 4.5,
            "operating_hours": hours("11:00-23:00"),
        },
        {
            "name": "Ocean Curry Leaf",
            "description": "Home-style rice and curry, open for breakfast and lunch.",
            "latitude": 6.427,
            "longitude": 79.996,
            "cuisine_type": "Local Sri Lankan",
            "avg_meal_cost": 8.00,
            "rating": 4.4,
            "operating_hours": hours("07:30-16:30"),
        },
        {
            "name": "River View Restaurant",
            "description": "River-side restaurant with Sri Lankan dishes and fresh fish.",
            "latitude": 6.434,
            "longitude": 80.003,
            "cuisine_type": "Local Sri Lankan",
            "avg_meal_cost": 13.00,
            "rating": 4.3,
            "operating_hours": hours("11:00-22:00"),
        },
        {
            "name": "Lanka Spice Indian Kitchen",
            "description": "Indian curries and tandoor specialities.",
            "latitude": 6.425,
            "longitude": 79.997,
            "cuisine_type": "Indian",
            "avg_meal_cost": 11.00,
            "rating": 4.2,
            "operating_hours": hours("11:00-22:30"),
        },
        {
            "name": "Palm Cafe Bentota",
            "description": "Casual cafe with sandwiches, pasta and smoothies.",
            "latitude": 6.423,
            "longitude": 79.994,
            "cuisine_type": "Western",
            "avg_meal_cost": 14.00,
            "rating": 4.3,
            "operating_hours": hours("08:00-22:00"),
        },
    ],
    "events": [
        {
            "name": "Bentota Water Sports Festival",
            "description": "Day of jet-ski races, windsurfing and beach games on the river mouth.",
            "latitude": 6.434,
            "longitude": 80.0,
            "entry_fee": 8.00,
            "rating": 4.4,
            "days_ahead": 70,
            "duration_days": 1,
            "start_time": "09:00",
            "end_time": "17:00",
        },
        {
            "name": "Bentota Sunset Music Night",
            "description": "Open-air sunset concert with live bands on the beach.",
            "latitude": 6.419,
            "longitude": 79.992,
            "entry_fee": 12.00,
            "rating": 4.5,
            "days_ahead": 135,
            "duration_days": 1,
            "start_time": "16:30",
            "end_time": "21:30",
        },
    ],
}
