from app.core.seed_data._helpers import hours

DESTINATION = {
    "name": "Dambulla",
    "description": "Cultural Triangle town famous for its cave temple complex, with easy access to Sigiriya and Kandalama.",
    "country": "Sri Lanka",
    "region": "Central Province",
    "latitude": 7.8567,
    "longitude": 80.6492,
    "is_active": True,
    "attractions": [
        {
            "name": "Dambulla Royal Cave Temple",
            "description": "Five cave shrines with painted ceilings and over a hundred Buddha statues.",
            "latitude": 7.857,
            "longitude": 80.649,
            "entry_fee": 10.00,
            "duration_hours": 2.0,
            "rating": 4.7,
            "opening_hours": hours("07:00-19:00"),
        },
        {
            "name": "Golden Temple of Dambulla",
            "description": "Giant golden Buddha statue and Buddhist museum at the foot of the rock.",
            "latitude": 7.8585,
            "longitude": 80.65,
            "entry_fee": 0.00,
            "duration_hours": 1.0,
            "rating": 4.3,
            "opening_hours": hours("06:00-19:00"),
        },
        {
            "name": "Dambulla Rock Summit",
            "description": "Short climb to the top of the rock for views across the plains.",
            "latitude": 7.859,
            "longitude": 80.647,
            "entry_fee": 0.00,
            "duration_hours": 1.5,
            "rating": 4.2,
            "opening_hours": hours("06:00-18:00"),
        },
        {
            "name": "Ibbankatuwa Prehistoric Tombs",
            "description": "Ancient burial site dating back over two thousand years.",
            "latitude": 7.905,
            "longitude": 80.68,
            "entry_fee": 5.00,
            "duration_hours": 1.0,
            "rating": 4.0,
            "opening_hours": hours("08:00-17:00"),
        },
        {
            "name": "Popham Arboretum",
            "description": "Forest reserve with walking trails, orchids and birdlife.",
            "latitude": 7.853,
            "longitude": 80.69,
            "entry_fee": 5.00,
            "duration_hours": 2.0,
            "rating": 4.3,
            "opening_hours": hours("06:00-17:00"),
        },
        {
            "name": "Dambulla Dedicated Economic Centre",
            "description": "Huge wholesale market for fruit and vegetables, great for photos.",
            "latitude": 7.87,
            "longitude": 80.66,
            "entry_fee": 0.00,
            "duration_hours": 1.0,
            "rating": 3.9,
            "opening_hours": hours("06:00-18:00"),
        },
        {
            "name": "Sigiriya Rock Sunrise Tour",
            "description": "Early-morning guided climb of the famous rock fortress.",
            "latitude": 7.9572,
            "longitude": 80.7598,
            "entry_fee": 30.00,
            "duration_hours": 3.0,
            "rating": 4.9,
            "opening_hours": hours("06:30-17:30"),
        },
        {
            "name": "Nalanda Gedige",
            "description": "Unusual 8th-century stone shrine with Hindu-Buddhist architecture.",
            "latitude": 7.712,
            "longitude": 80.635,
            "entry_fee": 5.00,
            "duration_hours": 1.5,
            "rating": 4.1,
            "opening_hours": hours("08:00-17:00"),
        },
        {
            "name": "Kandalama Lake",
            "description": "Large reservoir with birdwatching and sunset views.",
            "latitude": 7.898,
            "longitude": 80.698,
            "entry_fee": 0.00,
            "duration_hours": 2.0,
            "rating": 4.4,
            "opening_hours": hours("06:00-18:00"),
        },
        {
            "name": "Hiriwadunna Village Tour",
            "description": "Village visit with a bullock-cart ride, boat trip and home-cooked lunch.",
            "latitude": 7.95,
            "longitude": 80.7,
            "entry_fee": 15.00,
            "duration_hours": 2.5,
            "rating": 4.5,
            "opening_hours": hours("08:00-17:00"),
        },
    ],
    "hotels": [
        {
            "name": "Dambulla Budget Inn",
            "description": "Simple rooms close to the bus stand and cave temple.",
            "latitude": 7.859,
            "longitude": 80.651,
            "price_per_night": 35.00,
            "facilities": ["WiFi", "Breakfast", "Fan"],
            "rating": 4.0,
        },
        {
            "name": "Cave View Resort",
            "description": "Comfortable resort with a pool and views of the rock.",
            "latitude": 7.852,
            "longitude": 80.645,
            "price_per_night": 100.00,
            "facilities": ["WiFi", "Pool", "Restaurant", "Breakfast"],
            "rating": 4.4,
        },
        {
            "name": "Kandalama Heights Hotel",
            "description": "Upscale lakeside hotel with infinity pool and spa.",
            "latitude": 7.895,
            "longitude": 80.7,
            "price_per_night": 180.00,
            "facilities": ["WiFi", "Pool", "Spa", "Restaurant", "Gym"],
            "rating": 4.7,
        },
    ],
    "restaurants": [
        {
            "name": "Dambulla Rice and Curry House",
            "description": "Village-style rice and curry, open for breakfast and lunch.",
            "latitude": 7.8575,
            "longitude": 80.648,
            "cuisine_type": "Local Sri Lankan",
            "avg_meal_cost": 8.00,
            "rating": 4.5,
            "operating_hours": hours("08:00-17:00"),
        },
        {
            "name": "Rock Garden Restaurant",
            "description": "Garden restaurant serving Sri Lankan buffet dinners.",
            "latitude": 7.855,
            "longitude": 80.651,
            "cuisine_type": "Local Sri Lankan",
            "avg_meal_cost": 13.00,
            "rating": 4.3,
            "operating_hours": hours("11:00-22:00"),
        },
        {
            "name": "Dambulla Spice Kitchen",
            "description": "North and South Indian curries and fresh breads.",
            "latitude": 7.856,
            "longitude": 80.647,
            "cuisine_type": "Indian",
            "avg_meal_cost": 11.00,
            "rating": 4.2,
            "operating_hours": hours("11:00-22:30"),
        },
        {
            "name": "Golden Wok Dambulla",
            "description": "Chinese stir-fries and noodle dishes.",
            "latitude": 7.858,
            "longitude": 80.652,
            "cuisine_type": "Chinese",
            "avg_meal_cost": 12.00,
            "rating": 4.1,
            "operating_hours": hours("11:30-22:00"),
        },
        {
            "name": "Cave Temple Bistro",
            "description": "Western bistro with pasta, grills and desserts.",
            "latitude": 7.8545,
            "longitude": 80.649,
            "cuisine_type": "Western",
            "avg_meal_cost": 18.00,
            "rating": 4.3,
            "operating_hours": hours("12:00-23:00"),
        },
    ],
    "events": [
        {
            "name": "Dambulla Vesak Lantern Festival",
            "description": "Evening festival of lanterns, pandals and devotional music around the cave temple.",
            "latitude": 7.86,
            "longitude": 80.653,
            "entry_fee": 5.00,
            "rating": 4.6,
            "days_ahead": 60,
            "duration_days": 1,
            "start_time": "18:00",
            "end_time": "22:00",
        },
        {
            "name": "Dambulla Heritage Market Day",
            "description": "Daytime market of crafts, spices and local food with folk performances.",
            "latitude": 7.862,
            "longitude": 80.656,
            "entry_fee": 4.00,
            "rating": 4.2,
            "days_ahead": 140,
            "duration_days": 1,
            "start_time": "09:00",
            "end_time": "16:00",
        },
    ],
}
