from app.core.seed_data._helpers import hours

DESTINATION = {
    "name": "Ella",
    "description": "Hill country town famous for tea estates and mountain views.",
    "country": "Sri Lanka",
    "region": "Uva Province",
    "latitude": 6.8667,
    "longitude": 81.0466,
    "is_active": True,
    "attractions": [
        {
            "name": "Nine Arch Bridge",
            "description": (
                "Iconic colonial-era railway viaduct between Ella and Demodara, "
                "set in tea country and best seen when a train crosses."
            ),
            "latitude": 6.8768,
            "longitude": 81.0608,
            "entry_fee": 0.00,
            "duration_hours": 1.5,
            "rating": 4.8,
            "opening_hours": hours("06:00-18:00"),
        },
        {
            "name": "Little Adam's Peak",
            "description": "Easy hike through tea fields to a sweeping viewpoint over Ella Gap.",
            "latitude": 6.8730,
            "longitude": 81.0560,
            "entry_fee": 0.00,
            "duration_hours": 2.5,
            "rating": 4.7,
            "opening_hours": hours("05:00-18:00"),
        },
        {
            "name": "Ella Rock",
            "description": "Full-morning hike along the railway and through forest to a summit view.",
            "latitude": 6.8500,
            "longitude": 81.0700,
            "entry_fee": 0.00,
            "duration_hours": 4.0,
            "rating": 4.6,
            "opening_hours": hours("05:00-16:00"),
        },
        {
            "name": "Ravana Falls",
            "description": "Wide roadside waterfall linked to the Ravana legend.",
            "latitude": 6.8397,
            "longitude": 81.0513,
            "entry_fee": 0.00,
            "duration_hours": 1.0,
            "rating": 4.4,
            "opening_hours": hours("06:00-18:00"),
        },
        {
            "name": "Ravana Cave",
            "description": "Limestone cave on a hillside, reached by a steep stairway.",
            "latitude": 6.8360,
            "longitude": 81.0480,
            "entry_fee": 3.00,
            "duration_hours": 1.5,
            "rating": 4.3,
            "opening_hours": hours("08:00-17:00"),
        },
        {
            "name": "Demodara Loop",
            "description": "Famous spiral railway loop where the track passes over itself.",
            "latitude": 6.8800,
            "longitude": 81.0730,
            "entry_fee": 0.00,
            "duration_hours": 1.0,
            "rating": 4.2,
            "opening_hours": hours("06:00-18:00"),
        },
        {
            "name": "Flying Ravana Zip Line",
            "description": "Zip line across a tea valley with views of the hills.",
            "latitude": 6.8610,
            "longitude": 81.0420,
            "entry_fee": 25.00,
            "duration_hours": 1.5,
            "rating": 4.5,
            "opening_hours": hours("09:00-17:00"),
        },
        {
            "name": "Ella Spice Garden",
            "description": "Guided walk through a working spice garden with tastings.",
            "latitude": 6.8590,
            "longitude": 81.0480,
            "entry_fee": 5.00,
            "duration_hours": 1.5,
            "rating": 4.1,
            "opening_hours": hours("08:00-17:00"),
        },
        {
            "name": "Uva Halpewatte Tea Factory",
            "description": "Working tea factory offering tours and tea tasting.",
            "latitude": 6.8980,
            "longitude": 81.0260,
            "entry_fee": 5.00,
            "duration_hours": 1.5,
            "rating": 4.4,
            "opening_hours": hours("08:30-16:30", sunday="closed"),
        },
        {
            "name": "Lipton's Seat",
            "description": "Hilltop lookout above tea estates with views across the south.",
            "latitude": 6.7690,
            "longitude": 80.9610,
            "entry_fee": 0.00,
            "duration_hours": 2.5,
            "rating": 4.6,
            "opening_hours": hours("05:30-17:00"),
        },
    ],
    "hotels": [
        {
            "name": "Ella Budget Lodge",
            "description": "Simple, friendly guesthouse a short walk from the main street.",
            "latitude": 6.8680,
            "longitude": 81.0480,
            "price_per_night": 38.00,
            "facilities": ["WiFi", "Breakfast", "Hot Water"],
            "rating": 4.1,
        },
        {
            "name": "Ella Tea Hills Retreat",
            "description": "Mid-range hotel among tea fields with valley-view rooms.",
            "latitude": 6.8550,
            "longitude": 81.0600,
            "price_per_night": 85.00,
            "facilities": ["WiFi", "Restaurant", "Breakfast", "Parking"],
            "rating": 4.4,
        },
        {
            "name": "Ella Mountain Heights Resort",
            "description": "Upscale hillside resort with a pool and panoramic Ella Gap views.",
            "latitude": 6.8480,
            "longitude": 81.0390,
            "price_per_night": 160.00,
            "facilities": ["WiFi", "Pool", "Spa", "Restaurant", "Parking"],
            "rating": 4.7,
        },
    ],
    "restaurants": [
        {
            "name": "Ella Rice and Curry Corner",
            "description": "Home-style Sri Lankan rice and curry, open for breakfast and lunch.",
            "latitude": 6.8662,
            "longitude": 81.0470,
            "cuisine_type": "Local Sri Lankan",
            "avg_meal_cost": 8.00,
            "rating": 4.5,
            "operating_hours": hours("07:00-16:00"),
        },
        {
            "name": "Ella Spice Kitchen",
            "description": "Indian curries, dosas and fresh breads on the main street.",
            "latitude": 6.8670,
            "longitude": 81.0455,
            "cuisine_type": "Indian",
            "avg_meal_cost": 11.00,
            "rating": 4.3,
            "operating_hours": hours("11:00-22:00"),
        },
        {
            "name": "Mountain Cafe Ella",
            "description": "Relaxed cafe serving breakfasts, burgers and good coffee.",
            "latitude": 6.8655,
            "longitude": 81.0462,
            "cuisine_type": "Western",
            "avg_meal_cost": 14.00,
            "rating": 4.4,
            "operating_hours": hours("08:00-22:00"),
        },
        {
            "name": "Ella Pizza Terrace",
            "description": "Wood-fired pizza and pasta on a terrace with valley views.",
            "latitude": 6.8648,
            "longitude": 81.0475,
            "cuisine_type": "Western",
            "avg_meal_cost": 16.00,
            "rating": 4.2,
            "operating_hours": hours("12:00-23:00"),
        },
        {
            "name": "Ella Wok House",
            "description": "Fried rice, noodles and Sri Lankan-Chinese favourites.",
            "latitude": 6.8672,
            "longitude": 81.0445,
            "cuisine_type": "Chinese",
            "avg_meal_cost": 12.00,
            "rating": 4.1,
            "operating_hours": hours("11:30-22:30"),
        },
    ],
    "events": [
        {
            "name": "Ella Tea and Railway Festival",
            "description": "Festival celebrating hill-country tea and the scenic railway, with tastings and photo walks.",
            "latitude": 6.8690,
            "longitude": 81.0500,
            "entry_fee": 6.00,
            "rating": 4.4,
            "days_ahead": 55,
            "duration_days": 1,
            "start_time": "10:00",
            "end_time": "18:00",
        },
        {
            "name": "Ella Hill Country Food Fair",
            "description": "Evening fair of regional street food, local music and craft stalls.",
            "latitude": 6.8640,
            "longitude": 81.0440,
            "entry_fee": 5.00,
            "rating": 4.3,
            "days_ahead": 150,
            "duration_days": 1,
            "start_time": "16:00",
            "end_time": "21:00",
        },
    ],
    # Duplicate Nine Arch Bridge rows created earlier by manual data entry.
    "deactivate_attractions": ["Nine Arches Bridge"],
}
