from app.core.seed_data._helpers import hours

DESTINATION = {
    "name": "Jaffna",
    "description": "Cultural capital of the north, known for Hindu temples, a Dutch fort, distinctive cuisine and island beaches.",
    "country": "Sri Lanka",
    "region": "Northern Province",
    "latitude": 9.6615,
    "longitude": 80.0255,
    "is_active": True,
    "attractions": [
        {
            "name": "Nallur Kandaswamy Kovil",
            "description": "Grand Hindu temple with a golden gopuram and daily puja ceremonies.",
            "latitude": 9.674,
            "longitude": 80.03,
            "entry_fee": 0.00,
            "duration_hours": 1.5,
            "rating": 4.8,
            "opening_hours": hours("05:00-20:00"),
        },
        {
            "name": "Jaffna Fort",
            "description": "Large star-shaped Dutch fort beside the lagoon.",
            "latitude": 9.667,
            "longitude": 80.008,
            "entry_fee": 0.00,
            "duration_hours": 2.0,
            "rating": 4.4,
            "opening_hours": hours("08:00-18:00"),
        },
        {
            "name": "Jaffna Public Library",
            "description": "Iconic white library, rebuilt after 1981, with a quiet reading hall.",
            "latitude": 9.66,
            "longitude": 80.011,
            "entry_fee": 0.00,
            "duration_hours": 1.0,
            "rating": 4.3,
            "opening_hours": hours("09:00-17:00"),
        },
        {
            "name": "Jaffna Archaeological Museum",
            "description": "Small museum of regional sculptures, coins and pottery.",
            "latitude": 9.662,
            "longitude": 80.016,
            "entry_fee": 3.00,
            "duration_hours": 1.5,
            "rating": 4.0,
            "opening_hours": hours("09:00-17:00"),
        },
        {
            "name": "Keerimalai Springs",
            "description": "Natural freshwater springs beside the sea, long considered healing.",
            "latitude": 9.813,
            "longitude": 80.009,
            "entry_fee": 2.00,
            "duration_hours": 1.5,
            "rating": 4.2,
            "opening_hours": hours("06:00-18:00"),
        },
        {
            "name": "Casuarina Beach",
            "description": "Calm shallow beach shaded by casuarina trees.",
            "latitude": 9.797,
            "longitude": 79.88,
            "entry_fee": 0.00,
            "duration_hours": 2.5,
            "rating": 4.4,
            "opening_hours": hours("06:00-18:00"),
        },
        {
            "name": "Dambakola Patuna Temple",
            "description": "Coastal temple on the site where the Sri Maha Bodhi sapling arrived.",
            "latitude": 9.749,
            "longitude": 79.914,
            "entry_fee": 0.00,
            "duration_hours": 1.0,
            "rating": 4.1,
            "opening_hours": hours("06:00-18:00"),
        },
        {
            "name": "Kantharodai Buddhist Ruins",
            "description": "Field of small stone stupas from an ancient Buddhist settlement.",
            "latitude": 9.736,
            "longitude": 80.015,
            "entry_fee": 0.00,
            "duration_hours": 1.0,
            "rating": 4.0,
            "opening_hours": hours("08:00-17:00"),
        },
        {
            "name": "Jaffna Central Market",
            "description": "Busy market for palmyra products, spices and fresh seafood.",
            "latitude": 9.6648,
            "longitude": 80.014,
            "entry_fee": 0.00,
            "duration_hours": 1.5,
            "rating": 4.1,
            "opening_hours": hours("05:00-18:00"),
        },
        {
            "name": "Naguleswaram Temple",
            "description": "Ancient Shiva temple beside Keerimalai Springs.",
            "latitude": 9.814,
            "longitude": 80.01,
            "entry_fee": 0.00,
            "duration_hours": 1.0,
            "rating": 4.3,
            "opening_hours": hours("05:00-19:00"),
        },
    ],
    "hotels": [
        {
            "name": "Jaffna Budget Rest",
            "description": "Simple air-conditioned rooms close to the bus station.",
            "latitude": 9.664,
            "longitude": 80.022,
            "price_per_night": 30.00,
            "facilities": ["WiFi", "Breakfast", "Air Conditioning"],
            "rating": 4.0,
        },
        {
            "name": "Nallur Heritage Hotel",
            "description": "Mid-range hotel in a restored mansion near the temple.",
            "latitude": 9.67,
            "longitude": 80.028,
            "price_per_night": 85.00,
            "facilities": ["WiFi", "Restaurant", "Breakfast", "Garden"],
            "rating": 4.3,
        },
        {
            "name": "Northern Pearl Resort",
            "description": "Upscale city hotel with pool, spa and rooftop restaurant.",
            "latitude": 9.656,
            "longitude": 80.03,
            "price_per_night": 150.00,
            "facilities": ["WiFi", "Pool", "Spa", "Restaurant", "Gym"],
            "rating": 4.6,
        },
    ],
    "restaurants": [
        {
            "name": "Jaffna Crab Curry House",
            "description": "Local home of the famous Jaffna crab curry and rice dishes.",
            "latitude": 9.663,
            "longitude": 80.024,
            "cuisine_type": "Local Sri Lankan",
            "avg_meal_cost": 14.00,
            "rating": 4.7,
            "operating_hours": hours("11:00-22:00"),
        },
        {
            "name": "Jaffna Idli Corner",
            "description": "Breakfast and lunch spot for idli, dosa and vegetarian thalis.",
            "latitude": 9.665,
            "longitude": 80.023,
            "cuisine_type": "Indian",
            "avg_meal_cost": 6.00,
            "rating": 4.4,
            "operating_hours": hours("06:30-15:00"),
        },
        {
            "name": "Palmyra Seafood Grill",
            "description": "Evening seafood grill with prawn curry and grilled fish.",
            "latitude": 9.658,
            "longitude": 80.027,
            "cuisine_type": "Seafood",
            "avg_meal_cost": 22.00,
            "rating": 4.6,
            "operating_hours": hours("17:00-23:00"),
        },
        {
            "name": "Jaffna Fort Cafe",
            "description": "Cafe with sandwiches, pasta and coffee near the fort.",
            "latitude": 9.666,
            "longitude": 80.01,
            "cuisine_type": "Western",
            "avg_meal_cost": 12.00,
            "rating": 4.2,
            "operating_hours": hours("08:00-22:00"),
        },
        {
            "name": "Fort Road Chinese",
            "description": "Chinese restaurant with noodles, fried rice and devilled prawns.",
            "latitude": 9.661,
            "longitude": 80.019,
            "cuisine_type": "Chinese",
            "avg_meal_cost": 11.00,
            "rating": 4.0,
            "operating_hours": hours("11:30-22:00"),
        },
    ],
    "events": [
        {
            "name": "Nallur Temple Festival",
            "description": "Grand annual temple festival with chariot processions and devotional music.",
            "latitude": 9.6735,
            "longitude": 80.0295,
            "entry_fee": 0.00,
            "rating": 4.8,
            "days_ahead": 60,
            "duration_days": 1,
            "start_time": "16:00",
            "end_time": "22:00",
        },
        {
            "name": "Jaffna Palmyra Heritage Fair",
            "description": "Daytime fair of palmyra crafts, northern cuisine and folk arts.",
            "latitude": 9.664,
            "longitude": 80.018,
            "entry_fee": 5.00,
            "rating": 4.3,
            "days_ahead": 145,
            "duration_days": 1,
            "start_time": "10:00",
            "end_time": "17:00",
        },
    ],
}
