from app.core.seed_data._helpers import hours

DESTINATION = {
    "name": "Mirissa",
    "description": (
        "A laid-back south-coast beach town known for whale watching, surfing "
        "and palm-fringed bays."
    ),
    "country": "Sri Lanka",
    "region": "Southern Province",
    "latitude": 5.9483,
    "longitude": 80.4716,
    "is_active": True,
    "attractions": [
        {
            "name": "Mirissa Beach",
            "description": "Crescent bay with golden sand, gentle swimming and sunset views.",
            "latitude": 5.9460,
            "longitude": 80.4580,
            "entry_fee": 0.00,
            "duration_hours": 3.0,
            "rating": 4.7,
            "opening_hours": hours("06:00-18:00"),
        },
        {
            "name": "Parrot Rock",
            "description": "Rocky outcrop reached by wading at low tide, popular for photos.",
            "latitude": 5.9435,
            "longitude": 80.4590,
            "entry_fee": 0.00,
            "duration_hours": 1.0,
            "rating": 4.3,
            "opening_hours": hours("06:00-18:00"),
        },
        {
            "name": "Coconut Tree Hill",
            "description": "Palm-covered headland with a famous ocean viewpoint.",
            "latitude": 5.9400,
            "longitude": 80.4555,
            "entry_fee": 0.00,
            "duration_hours": 1.0,
            "rating": 4.6,
            "opening_hours": hours("05:30-18:30"),
        },
        {
            "name": "Mirissa Whale Watching Tour",
            "description": "Half-day boat trip from the harbour to spot blue whales, sperm whales and dolphins.",
            "latitude": 5.9437,
            "longitude": 80.4529,
            "entry_fee": 45.00,
            "duration_hours": 4.0,
            "rating": 4.8,
            "opening_hours": hours("06:00-14:00"),
        },
        {
            "name": "Secret Beach",
            "description": "Quiet cove hidden behind the headland, good for swimming.",
            "latitude": 5.9420,
            "longitude": 80.4440,
            "entry_fee": 0.00,
            "duration_hours": 2.0,
            "rating": 4.5,
            "opening_hours": hours("06:00-18:00"),
        },
        {
            "name": "Weligama Beach",
            "description": "Long sheltered bay popular with beginner surfers and stilt fishermen.",
            "latitude": 5.9745,
            "longitude": 80.4260,
            "entry_fee": 0.00,
            "duration_hours": 3.0,
            "rating": 4.4,
            "opening_hours": hours("06:00-18:00"),
        },
        {
            "name": "Weligama Surf Lesson",
            "description": "Beginner surf lesson with board and instructor included.",
            "latitude": 5.9720,
            "longitude": 80.4310,
            "entry_fee": 20.00,
            "duration_hours": 2.0,
            "rating": 4.6,
            "opening_hours": hours("07:00-17:00"),
        },
        {
            "name": "Polhena Reef",
            "description": "Calm reef lagoon for snorkelling with turtles.",
            "latitude": 5.9380,
            "longitude": 80.5330,
            "entry_fee": 10.00,
            "duration_hours": 2.0,
            "rating": 4.4,
            "opening_hours": hours("07:00-17:00"),
        },
        {
            "name": "Dondra Head Lighthouse",
            "description": "Tall lighthouse on the southernmost point of Sri Lanka.",
            "latitude": 5.9220,
            "longitude": 80.5920,
            "entry_fee": 5.00,
            "duration_hours": 1.0,
            "rating": 4.2,
            "opening_hours": hours("08:00-17:00"),
        },
        {
            "name": "Kataluwa Purana Viharaya",
            "description": "Old temple known for its well-preserved Kandyan-era murals.",
            "latitude": 5.9970,
            "longitude": 80.3940,
            "entry_fee": 3.00,
            "duration_hours": 1.0,
            "rating": 4.3,
            "opening_hours": hours("08:00-17:00"),
        },
    ],
    "hotels": [
        {
            "name": "Mirissa Beach Hostel",
            "description": "Budget beachside guesthouse with dorms and private rooms.",
            "latitude": 5.9470,
            "longitude": 80.4600,
            "price_per_night": 30.00,
            "facilities": ["WiFi", "Breakfast", "Fan"],
            "rating": 4.0,
        },
        {
            "name": "Palm Bay Mirissa",
            "description": "Mid-range hotel a short walk from the beach, with a pool.",
            "latitude": 5.9490,
            "longitude": 80.4650,
            "price_per_night": 90.00,
            "facilities": ["WiFi", "Pool", "Restaurant", "Breakfast"],
            "rating": 4.4,
        },
        {
            "name": "Mirissa Cliff Resort",
            "description": "Luxury clifftop resort with ocean-view suites and a spa.",
            "latitude": 5.9400,
            "longitude": 80.4700,
            "price_per_night": 190.00,
            "facilities": ["WiFi", "Pool", "Spa", "Fine Dining", "Sea View"],
            "rating": 4.8,
        },
    ],
    "restaurants": [
        {
            "name": "Mirissa Beach Shack",
            "description": "Beachfront shack serving fresh seafood and cold drinks all day.",
            "latitude": 5.9465,
            "longitude": 80.4585,
            "cuisine_type": "Seafood",
            "avg_meal_cost": 18.00,
            "rating": 4.5,
            "operating_hours": hours("11:00-23:00"),
        },
        {
            "name": "Fisherman's Grill",
            "description": "Evening grill with the day's catch laid out on ice.",
            "latitude": 5.9455,
            "longitude": 80.4540,
            "cuisine_type": "Seafood",
            "avg_meal_cost": 26.00,
            "rating": 4.7,
            "operating_hours": hours("17:00-23:00"),
        },
        {
            "name": "Mirissa Curry Leaf",
            "description": "Family-run rice and curry spot, open for breakfast and lunch.",
            "latitude": 5.9480,
            "longitude": 80.4620,
            "cuisine_type": "Local Sri Lankan",
            "avg_meal_cost": 8.00,
            "rating": 4.4,
            "operating_hours": hours("07:30-16:30"),
        },
        {
            "name": "Surf Cafe Mirissa",
            "description": "Casual cafe with smoothie bowls, burgers and surf videos.",
            "latitude": 5.9475,
            "longitude": 80.4610,
            "cuisine_type": "Western",
            "avg_meal_cost": 14.00,
            "rating": 4.3,
            "operating_hours": hours("08:00-22:00"),
        },
        {
            "name": "Lotus Indian Kitchen",
            "description": "South Indian and Sri Lankan curries, with many vegetarian dishes.",
            "latitude": 5.9495,
            "longitude": 80.4635,
            "cuisine_type": "Indian",
            "avg_meal_cost": 12.00,
            "rating": 4.2,
            "operating_hours": hours("11:00-22:30"),
        },
    ],
    "events": [
        {
            "name": "Mirissa Whale and Ocean Festival",
            "description": "Beach festival with marine-conservation talks, food stalls and live music.",
            "latitude": 5.9450,
            "longitude": 80.4570,
            "entry_fee": 7.00,
            "rating": 4.5,
            "days_ahead": 90,
            "duration_days": 1,
            "start_time": "10:00",
            "end_time": "20:00",
        },
        {
            "name": "Mirissa Beach Music Night",
            "description": "Open-air sunset gig with DJs and local bands on the sand.",
            "latitude": 5.9468,
            "longitude": 80.4560,
            "entry_fee": 12.00,
            "rating": 4.4,
            "days_ahead": 130,
            "duration_days": 1,
            "start_time": "17:00",
            "end_time": "22:00",
        },
    ],
}
