from app.core.seed_data._helpers import hours

DESTINATION = {
    "name": "Negombo",
    "description": "Lively fishing town and beach resort near the airport, with a lagoon, canals and a Dutch fort.",
    "country": "Sri Lanka",
    "region": "Western Province",
    "latitude": 7.2086,
    "longitude": 79.8358,
    "is_active": True,
    "attractions": [
        {
            "name": "Negombo Beach",
            "description": "Long sandy beach lined with fishing boats and sunset cafes.",
            "latitude": 7.22,
            "longitude": 79.838,
            "entry_fee": 0.00,
            "duration_hours": 3.0,
            "rating": 4.3,
            "opening_hours": hours("06:00-18:00"),
        },
        {
            "name": "Negombo Lagoon Boat Tour",
            "description": "Outrigger boat trip through mangroves and fishing villages.",
            "latitude": 7.2,
            "longitude": 79.84,
            "entry_fee": 15.00,
            "duration_hours": 2.5,
            "rating": 4.5,
            "opening_hours": hours("06:00-17:00"),
        },
        {
            "name": "Negombo Dutch Fort Gate",
            "description": "Remains of the 17th-century Dutch fort beside the old prison.",
            "latitude": 7.2125,
            "longitude": 79.84,
            "entry_fee": 0.00,
            "duration_hours": 1.0,
            "rating": 4.0,
            "opening_hours": hours("08:00-17:00"),
        },
        {
            "name": "Saint Mary's Church Negombo",
            "description": "Grand Catholic church with a painted ceiling, in Little Rome.",
            "latitude": 7.206,
            "longitude": 79.835,
            "entry_fee": 0.00,
            "duration_hours": 1.0,
            "rating": 4.4,
            "opening_hours": hours("06:00-18:00"),
        },
        {
            "name": "Angurukaramulla Temple",
            "description": "Buddhist temple known for its colourful murals and a huge reclining Buddha.",
            "latitude": 7.217,
            "longitude": 79.82,
            "entry_fee": 3.00,
            "duration_hours": 1.0,
            "rating": 4.3,
            "opening_hours": hours("06:00-18:00"),
        },
        {
            "name": "Negombo Fish Market",
            "description": "Busy morning market where the day's catch is sold and dried.",
            "latitude": 7.211,
            "longitude": 79.837,
            "entry_fee": 0.00,
            "duration_hours": 1.5,
            "rating": 4.1,
            "opening_hours": hours("05:00-13:00"),
        },
        {
            "name": "Muthurajawela Wetland Sanctuary",
            "description": "Coastal marsh with birdlife, boat rides and mangrove walks.",
            "latitude": 7.165,
            "longitude": 79.87,
            "entry_fee": 12.00,
            "duration_hours": 2.5,
            "rating": 4.4,
            "opening_hours": hours("07:00-17:00"),
        },
        {
            "name": "Hamilton Canal Cruise",
            "description": "Relaxed canal cruise past old Dutch-era waterways.",
            "latitude": 7.19,
            "longitude": 79.86,
            "entry_fee": 10.00,
            "duration_hours": 2.0,
            "rating": 4.2,
            "opening_hours": hours("08:00-17:00"),
        },
        {
            "name": "Duwa Sea Church",
            "description": "Island church known for its Passion Play pilgrimage.",
            "latitude": 7.261,
            "longitude": 79.833,
            "entry_fee": 0.00,
            "duration_hours": 1.0,
            "rating": 4.1,
            "opening_hours": hours("07:00-18:00"),
        },
        {
            "name": "Negombo Batik Workshop",
            "description": "Hands-on workshop where visitors try block printing and batik dyeing.",
            "latitude": 7.2,
            "longitude": 79.85,
            "entry_fee": 5.00,
            "duration_hours": 1.5,
            "rating": 4.0,
            "opening_hours": hours("09:00-17:00"),
        },
    ],
    "hotels": [
        {
            "name": "Negombo Budget Guesthouse",
            "description": "Simple rooms a short ride from the beach and airport.",
            "latitude": 7.215,
            "longitude": 79.836,
            "price_per_night": 30.00,
            "facilities": ["WiFi", "Breakfast", "Air Conditioning"],
            "rating": 4.0,
        },
        {
            "name": "Lagoon Palms Hotel",
            "description": "Mid-range hotel beside the lagoon with a pool.",
            "latitude": 7.202,
            "longitude": 79.838,
            "price_per_night": 95.00,
            "facilities": ["WiFi", "Pool", "Restaurant", "Breakfast"],
            "rating": 4.3,
        },
        {
            "name": "Sea Breeze Negombo Resort",
            "description": "Upscale beachfront resort with spa and sea-view rooms.",
            "latitude": 7.23,
            "longitude": 79.839,
            "price_per_night": 165.00,
            "facilities": ["WiFi", "Pool", "Spa", "Restaurant", "Sea View"],
            "rating": 4.6,
        },
    ],
    "restaurants": [
        {
            "name": "Negombo Curry Pot",
            "description": "Traditional rice and curry with fresh sambols, open until late afternoon.",
            "latitude": 7.21,
            "longitude": 79.835,
            "cuisine_type": "Local Sri Lankan",
            "avg_meal_cost": 8.00,
            "rating": 4.4,
            "operating_hours": hours("07:30-16:30"),
        },
        {
            "name": "Fishermans Wharf Grill",
            "description": "Evening seafood grill beside the fishing harbour.",
            "latitude": 7.209,
            "longitude": 79.838,
            "cuisine_type": "Seafood",
            "avg_meal_cost": 24.00,
            "rating": 4.7,
            "operating_hours": hours("17:00-23:00"),
        },
        {
            "name": "Lagoon Side Bistro",
            "description": "Western bistro overlooking the lagoon with pasta and grills.",
            "latitude": 7.204,
            "longitude": 79.839,
            "cuisine_type": "Western",
            "avg_meal_cost": 18.00,
            "rating": 4.3,
            "operating_hours": hours("12:00-23:00"),
        },
        {
            "name": "Spice Route Indian Kitchen",
            "description": "North Indian curries and tandoor dishes.",
            "latitude": 7.213,
            "longitude": 79.834,
            "cuisine_type": "Indian",
            "avg_meal_cost": 11.00,
            "rating": 4.2,
            "operating_hours": hours("11:00-22:30"),
        },
        {
            "name": "Golden Dragon Negombo",
            "description": "Chinese restaurant with seafood noodles and fried rice.",
            "latitude": 7.207,
            "longitude": 79.837,
            "cuisine_type": "Chinese",
            "avg_meal_cost": 12.00,
            "rating": 4.0,
            "operating_hours": hours("11:30-22:00"),
        },
    ],
    "events": [
        {
            "name": "Negombo Fish Festival",
            "description": "Seaside festival of grilled seafood, cooking demos and fishing-boat parades.",
            "latitude": 7.218,
            "longitude": 79.837,
            "entry_fee": 6.00,
            "rating": 4.4,
            "days_ahead": 55,
            "duration_days": 1,
            "start_time": "10:00",
            "end_time": "20:00",
        },
        {
            "name": "Negombo Lagoon Lantern Night",
            "description": "Evening lantern boat procession on the lagoon with live drumming.",
            "latitude": 7.201,
            "longitude": 79.842,
            "entry_fee": 8.00,
            "rating": 4.5,
            "days_ahead": 125,
            "duration_days": 1,
            "start_time": "17:30",
            "end_time": "21:30",
        },
    ],
}
