from app.core.seed_data._helpers import hours

DESTINATION = {
    "name": "Nuwara Eliya",
    "description": (
        "A cool hill-country town known as Little England, surrounded by tea "
        "estates, gardens, waterfalls and Horton Plains."
    ),
    "country": "Sri Lanka",
    "region": "Central Province",
    "latitude": 6.9497,
    "longitude": 80.7891,
    "is_active": True,
    "attractions": [
        {
            "name": "Gregory Lake",
            "description": "Large lake in the town centre with boating and lakeside walks.",
            "latitude": 6.9560,
            "longitude": 80.7830,
            "entry_fee": 2.00,
            "duration_hours": 2.0,
            "rating": 4.4,
            "opening_hours": hours("06:00-18:00"),
        },
        {
            "name": "Victoria Park",
            "description": "Well-kept public park with flower beds and birdlife.",
            "latitude": 6.9707,
            "longitude": 80.7690,
            "entry_fee": 3.00,
            "duration_hours": 2.0,
            "rating": 4.3,
            "opening_hours": hours("07:00-18:00"),
        },
        {
            "name": "Horton Plains National Park",
            "description": "High-altitude plateau with the World's End cliff and Baker's Falls trail.",
            "latitude": 6.8020,
            "longitude": 80.8010,
            "entry_fee": 30.00,
            "duration_hours": 4.0,
            "rating": 4.8,
            "opening_hours": hours("06:00-16:00"),
        },
        {
            "name": "Pedro Tea Estate",
            "description": "Tea estate and factory with guided tours and tasting.",
            "latitude": 6.9545,
            "longitude": 80.7720,
            "entry_fee": 3.00,
            "duration_hours": 1.5,
            "rating": 4.5,
            "opening_hours": hours("08:00-16:30"),
        },
        {
            "name": "Lover's Leap Waterfall",
            "description": "Pretty waterfall reached by a short walk through tea fields.",
            "latitude": 6.9650,
            "longitude": 80.7640,
            "entry_fee": 0.00,
            "duration_hours": 1.5,
            "rating": 4.3,
            "opening_hours": hours("07:00-17:00"),
        },
        {
            "name": "Hakgala Botanical Garden",
            "description": "Cool-climate botanical garden with roses, ferns and mountain views.",
            "latitude": 6.9250,
            "longitude": 80.8230,
            "entry_fee": 10.00,
            "duration_hours": 2.5,
            "rating": 4.5,
            "opening_hours": hours("08:00-17:00"),
        },
        {
            "name": "St. Clair's Falls",
            "description": "Broad two-tier waterfall known as the Little Niagara of Sri Lanka.",
            "latitude": 6.9380,
            "longitude": 80.6540,
            "entry_fee": 0.00,
            "duration_hours": 1.0,
            "rating": 4.4,
            "opening_hours": hours("06:00-18:00"),
        },
        {
            "name": "Single Tree Hill",
            "description": "Short climb to a hilltop viewpoint over the town and lake.",
            "latitude": 6.9340,
            "longitude": 80.7540,
            "entry_fee": 0.00,
            "duration_hours": 1.5,
            "rating": 4.2,
            "opening_hours": hours("06:00-18:00"),
        },
        {
            "name": "Ambewela Farm",
            "description": "Highland dairy farm with rolling pastures and fresh dairy products.",
            "latitude": 6.8470,
            "longitude": 80.8070,
            "entry_fee": 3.00,
            "duration_hours": 2.0,
            "rating": 4.2,
            "opening_hours": hours("08:00-17:00"),
        },
        {
            "name": "Seetha Amman Temple",
            "description": "Colourful Hindu temple associated with the Ramayana legend.",
            "latitude": 6.9180,
            "longitude": 80.8130,
            "entry_fee": 0.00,
            "duration_hours": 1.0,
            "rating": 4.1,
            "opening_hours": hours("06:00-18:00"),
        },
    ],
    "hotels": [
        {
            "name": "Nuwara Eliya Budget Inn",
            "description": "Clean, affordable rooms close to the bus stand and market.",
            "latitude": 6.9530,
            "longitude": 80.7870,
            "price_per_night": 40.00,
            "facilities": ["WiFi", "Breakfast", "Hot Water", "Heating"],
            "rating": 4.0,
        },
        {
            "name": "Colonial Heights Lodge",
            "description": "Heritage-style lodge with fireplaces and manicured gardens.",
            "latitude": 6.9480,
            "longitude": 80.7950,
            "price_per_night": 120.00,
            "facilities": ["WiFi", "Restaurant", "Garden", "Heating", "Breakfast"],
            "rating": 4.5,
        },
        {
            "name": "Lake Gregory Grand",
            "description": "Upscale lakeside hotel with spa and lake-view suites.",
            "latitude": 6.9575,
            "longitude": 80.7845,
            "price_per_night": 175.00,
            "facilities": ["WiFi", "Spa", "Restaurant", "Gym", "Heating"],
            "rating": 4.7,
        },
    ],
    "restaurants": [
        {
            "name": "Highland Tea Room",
            "description": "Colonial-style tea room with scones, sandwiches and local tea.",
            "latitude": 6.9510,
            "longitude": 80.7880,
            "cuisine_type": "Local Sri Lankan",
            "avg_meal_cost": 9.00,
            "rating": 4.5,
            "operating_hours": hours("08:00-17:00"),
        },
        {
            "name": "Nuwara Eliya Curry House",
            "description": "Rice and curry with hill-country vegetables.",
            "latitude": 6.9490,
            "longitude": 80.7905,
            "cuisine_type": "Local Sri Lankan",
            "avg_meal_cost": 11.00,
            "rating": 4.3,
            "operating_hours": hours("11:00-22:00"),
        },
        {
            "name": "Hill Station Grill",
            "description": "Warm dining room serving grills, soups and hearty Western dishes.",
            "latitude": 6.9520,
            "longitude": 80.7920,
            "cuisine_type": "Western",
            "avg_meal_cost": 22.00,
            "rating": 4.4,
            "operating_hours": hours("12:00-23:00"),
        },
        {
            "name": "Lakeside Chinese Garden",
            "description": "Chinese restaurant overlooking Lake Gregory.",
            "latitude": 6.9568,
            "longitude": 80.7860,
            "cuisine_type": "Chinese",
            "avg_meal_cost": 15.00,
            "rating": 4.2,
            "operating_hours": hours("11:30-22:00"),
        },
        {
            "name": "Highland Indian Kitchen",
            "description": "North Indian curries and tandoor dishes, popular in the cold evenings.",
            "latitude": 6.9470,
            "longitude": 80.7860,
            "cuisine_type": "Indian",
            "avg_meal_cost": 14.00,
            "rating": 4.3,
            "operating_hours": hours("11:00-22:30"),
        },
    ],
    "events": [
        {
            "name": "Nuwara Eliya Spring Season Festival",
            "description": "Season festival with a flower show, street parade and live entertainment.",
            "latitude": 6.9600,
            "longitude": 80.7800,
            "entry_fee": 8.00,
            "rating": 4.6,
            "days_ahead": 45,
            "duration_days": 1,
            "start_time": "10:00",
            "end_time": "19:00",
        },
        {
            "name": "Highland Tea and Flower Show",
            "description": "Display of tea varieties and highland flowers with tasting sessions.",
            "latitude": 6.9535,
            "longitude": 80.7810,
            "entry_fee": 5.00,
            "rating": 4.3,
            "days_ahead": 160,
            "duration_days": 1,
            "start_time": "09:30",
            "end_time": "16:30",
        },
    ],
}
