"""Credits for the Wikimedia Commons photos used in the tourism seed.

Every entry is a 960px thumbnail served from upload.wikimedia.org, under CC0,
public domain, CC BY or CC BY-SA. ``kind`` is "attraction" (a real place, matched
by attraction name) or "generic" (a stand-in photo for fictional hotels,
restaurants and events; see commons_photos.py for how they are assigned).

Wikimedia only serves standard thumbnail widths; 800px returns HTTP 400, so 960px
is the nearest allowed size above 800.

Check that every URL still loads with: python -m app.core.check_seed_data --urls
"""

PHOTO_CREDITS = [
    {
        "kind": "attraction",
        "name": "Jetavanaramaya",
        "used_for": "Anuradhapura / Jetavanaramaya",
        "title": "File:Jetavanaramaya - Anuradhapura.jpg",
        "author": "Nipuna Gamage",
        "license": "CC BY-SA 4.0",
        "license_url": "https://creativecommons.org/licenses/by-sa/4.0",
        "source": "https://commons.wikimedia.org/wiki/File:Jetavanaramaya_-_Anuradhapura.jpg",
        "url": "https://upload.wikimedia.org/wikipedia/commons/thumb/f/f4/Jetavanaramaya_-_Anuradhapura.jpg/960px-Jetavanaramaya_-_Anuradhapura.jpg",
    },
    {
        "kind": "attraction",
        "name": "Ruwanwelisaya",
        "used_for": "Anuradhapura / Ruwanwelisaya",
        "title": "File:Ruwanweli Saya 1.jpg",
        "author": "KennyOMG",
        "license": "CC BY-SA 4.0",
        "license_url": "https://creativecommons.org/licenses/by-sa/4.0",
        "source": "https://commons.wikimedia.org/wiki/File:Ruwanweli_Saya_1.jpg",
        "url": "https://upload.wikimedia.org/wikipedia/commons/thumb/c/c2/Ruwanweli_Saya_1.jpg/960px-Ruwanweli_Saya_1.jpg",
    },
    {
        "kind": "attraction",
        "name": "Sri Maha Bodhi",
        "used_for": "Anuradhapura / Sri Maha Bodhi",
        "title": "File:Sri Maha Bodhi, Anuradhapura.jpg",
        "author": "Hirushini Dematagoda",
        "license": "CC BY-SA 4.0",
        "license_url": "https://creativecommons.org/licenses/by-sa/4.0",
        "source": "https://commons.wikimedia.org/wiki/File:Sri_Maha_Bodhi,_Anuradhapura.jpg",
        "url": "https://upload.wikimedia.org/wikipedia/commons/thumb/b/b1/Sri_Maha_Bodhi%2C_Anuradhapura.jpg/960px-Sri_Maha_Bodhi%2C_Anuradhapura.jpg",
    },
    {
        "kind": "attraction",
        "name": "Arugam Bay Beach",
        "used_for": "Arugam Bay / Arugam Bay Beach",
        "title": "File:Beach of Arugam Bay.jpg",
        "author": "Dennis Sylvester Hurd",
        "license": "CC0",
        "license_url": "http://creativecommons.org/publicdomain/zero/1.0/deed.en",
        "source": "https://commons.wikimedia.org/wiki/File:Beach_of_Arugam_Bay.jpg",
        "url": "https://upload.wikimedia.org/wikipedia/commons/thumb/2/2c/Beach_of_Arugam_Bay.jpg/960px-Beach_of_Arugam_Bay.jpg",
    },
    {
        "kind": "attraction",
        "name": "Muhudu Maha Viharaya",
        "used_for": "Arugam Bay / Muhudu Maha Viharaya",
        "title": "File:Muhudu Maha Viharaya (මුහුදු මහා විහාරය).jpg",
        "author": "Knthabrew",
        "license": "CC BY-SA 4.0",
        "license_url": "https://creativecommons.org/licenses/by-sa/4.0",
        "source": "https://commons.wikimedia.org/wiki/File:Muhudu_Maha_Viharaya_(%E0%B6%B8%E0%B7%94%E0%B7%84%E0%B7%94%E0%B6%AF%E0%B7%94_%E0%B6%B8%E0%B7%84%E0%B7%8F_%E0%B7%80%E0%B7%92%E0%B7%84%E0%B7%8F%E0%B6%BB%E0%B6%BA).jpg",
        "url": "https://upload.wikimedia.org/wikipedia/commons/thumb/c/c7/Muhudu_Maha_Viharaya_%28%E0%B6%B8%E0%B7%94%E0%B7%84%E0%B7%94%E0%B6%AF%E0%B7%94_%E0%B6%B8%E0%B7%84%E0%B7%8F_%E0%B7%80%E0%B7%92%E0%B7%84%E0%B7%8F%E0%B6%BB%E0%B6%BA%29.jpg/960px-Muhudu_Maha_Viharaya_%28%E0%B6%B8%E0%B7%94%E0%B7%84%E0%B7%94%E0%B6%AF%E0%B7%94_%E0%B6%B8%E0%B7%84%E0%B7%8F_%E0%B7%80%E0%B7%92%E0%B7%84%E0%B7%8F%E0%B6%BB%E0%B6%BA%29.jpg",
    },
    {
        "kind": "attraction",
        "name": "Whiskey Point Beach",
        "used_for": "Arugam Bay / Whiskey Point Beach",
        "title": "File:Whiskey Point 2.jpg",
        "author": "Kalana Jayatilake",
        "license": "CC BY-SA 4.0",
        "license_url": "https://creativecommons.org/licenses/by-sa/4.0",
        "source": "https://commons.wikimedia.org/wiki/File:Whiskey_Point_2.jpg",
        "url": "https://upload.wikimedia.org/wikipedia/commons/thumb/d/d0/Whiskey_Point_2.jpg/960px-Whiskey_Point_2.jpg",
    },
    {
        "kind": "attraction",
        "name": "Bentota Beach",
        "used_for": "Bentota / Bentota Beach",
        "title": "File:Sri Lanka, Bentota, beach (2).JPG",
        "author": "Vincent van Zeijst",
        "license": "CC BY-SA 3.0",
        "license_url": "https://creativecommons.org/licenses/by-sa/3.0",
        "source": "https://commons.wikimedia.org/wiki/File:Sri_Lanka,_Bentota,_beach_(2).JPG",
        "url": "https://upload.wikimedia.org/wikipedia/commons/thumb/c/c5/Sri_Lanka%2C_Bentota%2C_beach_%282%29.JPG/960px-Sri_Lanka%2C_Bentota%2C_beach_%282%29.JPG",
    },
    {
        "kind": "attraction",
        "name": "Lunuganga Estate",
        "used_for": "Bentota / Lunuganga Estate",
        "title": "File:Lunuganga - Bungalow Back.jpg",
        "author": "Eco2004",
        "license": "CC BY-SA 4.0",
        "license_url": "https://creativecommons.org/licenses/by-sa/4.0",
        "source": "https://commons.wikimedia.org/wiki/File:Lunuganga_-_Bungalow_Back.jpg",
        "url": "https://upload.wikimedia.org/wikipedia/commons/thumb/6/63/Lunuganga_-_Bungalow_Back.jpg/960px-Lunuganga_-_Bungalow_Back.jpg",
    },
    {
        "kind": "attraction",
        "name": "Madu River Boat Safari",
        "used_for": "Bentota / Madu River Boat Safari",
        "title": "File:Madu Ganga, Sri Lanka.jpg",
        "author": "briandemel",
        "license": "CC BY-SA 4.0",
        "license_url": "https://creativecommons.org/licenses/by-sa/4.0",
        "source": "https://commons.wikimedia.org/wiki/File:Madu_Ganga,_Sri_Lanka.jpg",
        "url": "https://upload.wikimedia.org/wikipedia/commons/thumb/7/7c/Madu_Ganga%2C_Sri_Lanka.jpg/960px-Madu_Ganga%2C_Sri_Lanka.jpg",
    },
    {
        "kind": "attraction",
        "name": "Colombo Lotus Tower",
        "used_for": "Colombo / Colombo Lotus Tower",
        "title": "File:Blue lotus tower.jpg",
        "author": "Mohamed Rilwan1210",
        "license": "CC BY-SA 4.0",
        "license_url": "https://creativecommons.org/licenses/by-sa/4.0",
        "source": "https://commons.wikimedia.org/wiki/File:Blue_lotus_tower.jpg",
        "url": "https://upload.wikimedia.org/wikipedia/commons/thumb/7/79/Blue_lotus_tower.jpg/960px-Blue_lotus_tower.jpg",
    },
    {
        "kind": "attraction",
        "name": "Dambulla Royal Cave Temple",
        "used_for": "Dambulla / Dambulla Royal Cave Temple",
        "title": "File:Dambulla Cave 1.jpg",
        "author": "Philip Nalangan",
        "license": "CC BY 4.0",
        "license_url": "https://creativecommons.org/licenses/by/4.0",
        "source": "https://commons.wikimedia.org/wiki/File:Dambulla_Cave_1.jpg",
        "url": "https://upload.wikimedia.org/wikipedia/commons/thumb/b/bd/Dambulla_Cave_1.jpg/960px-Dambulla_Cave_1.jpg",
    },
    {
        "kind": "attraction",
        "name": "Golden Temple of Dambulla",
        "used_for": "Dambulla / Golden Temple of Dambulla",
        "title": "File:Dambulla Temple d'or (3).jpg",
        "author": "PIERRE ANDRE LECLERCQ",
        "license": "CC BY-SA 4.0",
        "license_url": "https://creativecommons.org/licenses/by-sa/4.0",
        "source": "https://commons.wikimedia.org/wiki/File:Dambulla_Temple_d%27or_(3).jpg",
        "url": "https://upload.wikimedia.org/wikipedia/commons/thumb/0/05/Dambulla_Temple_d%27or_%283%29.jpg/960px-Dambulla_Temple_d%27or_%283%29.jpg",
    },
    {
        "kind": "attraction",
        "name": "Kandalama Lake",
        "used_for": "Dambulla / Kandalama Lake",
        "title": "File:Kandalama Lake.jpg",
        "author": "Manoj Samarakoon",
        "license": "CC BY-SA 4.0",
        "license_url": "https://creativecommons.org/licenses/by-sa/4.0",
        "source": "https://commons.wikimedia.org/wiki/File:Kandalama_Lake.jpg",
        "url": "https://upload.wikimedia.org/wikipedia/commons/thumb/9/92/Kandalama_Lake.jpg/960px-Kandalama_Lake.jpg",
    },
    {
        "kind": "attraction",
        "name": "Ella Rock",
        "used_for": "Ella / Ella Rock",
        "title": "File:Top of Ella Rock.jpg",
        "author": "Leeno2001",
        "license": "CC BY-SA 4.0",
        "license_url": "https://creativecommons.org/licenses/by-sa/4.0",
        "source": "https://commons.wikimedia.org/wiki/File:Top_of_Ella_Rock.jpg",
        "url": "https://upload.wikimedia.org/wikipedia/commons/thumb/d/d9/Top_of_Ella_Rock.jpg/960px-Top_of_Ella_Rock.jpg",
    },
    {
        "kind": "attraction",
        "name": "Little Adam's Peak",
        "used_for": "Ella / Little Adam's Peak",
        "title": "File:Little Adam's Peak, Ella, Sri Lanka.jpg",
        "author": "Bcd4e6",
        "license": "CC BY-SA 4.0",
        "license_url": "https://creativecommons.org/licenses/by-sa/4.0",
        "source": "https://commons.wikimedia.org/wiki/File:Little_Adam%27s_Peak,_Ella,_Sri_Lanka.jpg",
        "url": "https://upload.wikimedia.org/wikipedia/commons/thumb/d/d1/Little_Adam%27s_Peak%2C_Ella%2C_Sri_Lanka.jpg/960px-Little_Adam%27s_Peak%2C_Ella%2C_Sri_Lanka.jpg",
    },
    {
        "kind": "attraction",
        "name": "Nine Arch Bridge",
        "used_for": "Ella / Nine Arch Bridge",
        "title": "File:Nine arch bridge, Ella, Sri lanka.jpg",
        "author": "Ishan shanuka",
        "license": "CC BY-SA 4.0",
        "license_url": "https://creativecommons.org/licenses/by-sa/4.0",
        "source": "https://commons.wikimedia.org/wiki/File:Nine_arch_bridge,_Ella,_Sri_lanka.jpg",
        "url": "https://upload.wikimedia.org/wikipedia/commons/thumb/9/90/Nine_arch_bridge%2C_Ella%2C_Sri_lanka.jpg/960px-Nine_arch_bridge%2C_Ella%2C_Sri_lanka.jpg",
    },
    {
        "kind": "attraction",
        "name": "Galle Fort",
        "used_for": "Galle / Galle Fort",
        "title": "File:Galle Fort ramparts (23304598811).jpg",
        "author": "Ankur Panchbudhe from Pune, India",
        "license": "CC BY 2.0",
        "license_url": "https://creativecommons.org/licenses/by/2.0",
        "source": "https://commons.wikimedia.org/wiki/File:Galle_Fort_ramparts_(23304598811).jpg",
        "url": "https://upload.wikimedia.org/wikipedia/commons/thumb/a/a1/Galle_Fort_ramparts_%2823304598811%29.jpg/960px-Galle_Fort_ramparts_%2823304598811%29.jpg",
    },
    {
        "kind": "attraction",
        "name": "Galle Lighthouse",
        "used_for": "Galle / Galle Lighthouse",
        "title": "File:Galle Lighthouse 1.jpg",
        "author": "Philip Nalangan",
        "license": "CC BY 4.0",
        "license_url": "https://creativecommons.org/licenses/by/4.0",
        "source": "https://commons.wikimedia.org/wiki/File:Galle_Lighthouse_1.jpg",
        "url": "https://upload.wikimedia.org/wikipedia/commons/thumb/c/ce/Galle_Lighthouse_1.jpg/960px-Galle_Lighthouse_1.jpg",
    },
    {
        "kind": "attraction",
        "name": "Jaffna Fort",
        "used_for": "Jaffna / Jaffna Fort",
        "title": "File:Jaffna Fort (1).jpg",
        "author": "Rehman Abubakr",
        "license": "CC BY-SA 4.0",
        "license_url": "https://creativecommons.org/licenses/by-sa/4.0",
        "source": "https://commons.wikimedia.org/wiki/File:Jaffna_Fort_(1).jpg",
        "url": "https://upload.wikimedia.org/wikipedia/commons/thumb/7/79/Jaffna_Fort_%281%29.jpg/960px-Jaffna_Fort_%281%29.jpg",
    },
    {
        "kind": "attraction",
        "name": "Jaffna Public Library",
        "used_for": "Jaffna / Jaffna Public Library",
        "title": "File:Jaffna Public Library.jpg",
        "author": "Thamizhpparithi Maari",
        "license": "CC BY-SA 4.0",
        "license_url": "https://creativecommons.org/licenses/by-sa/4.0",
        "source": "https://commons.wikimedia.org/wiki/File:Jaffna_Public_Library.jpg",
        "url": "https://upload.wikimedia.org/wikipedia/commons/thumb/0/0d/Jaffna_Public_Library.jpg/960px-Jaffna_Public_Library.jpg",
    },
    {
        "kind": "attraction",
        "name": "Nallur Kandaswamy Kovil",
        "used_for": "Jaffna / Nallur Kandaswamy Kovil",
        "title": "File:Nallur Kandasamy front entrance.jpg",
        "author": "Gane Kumaraswamy",
        "license": "CC BY-SA 2.0",
        "license_url": "https://creativecommons.org/licenses/by-sa/2.0",
        "source": "https://commons.wikimedia.org/wiki/File:Nallur_Kandasamy_front_entrance.jpg",
        "url": "https://upload.wikimedia.org/wikipedia/commons/thumb/6/61/Nallur_Kandasamy_front_entrance.jpg/960px-Nallur_Kandasamy_front_entrance.jpg",
    },
    {
        "kind": "attraction",
        "name": "Royal Botanical Gardens",
        "used_for": "Kandy / Royal Botanical Gardens",
        "title": "File:Royal Botanic Gardens, Peradeniya.jpg",
        "author": "Dudva",
        "license": "CC0",
        "license_url": "http://creativecommons.org/publicdomain/zero/1.0/deed.en",
        "source": "https://commons.wikimedia.org/wiki/File:Royal_Botanic_Gardens,_Peradeniya.jpg",
        "url": "https://upload.wikimedia.org/wikipedia/commons/thumb/8/82/Royal_Botanic_Gardens%2C_Peradeniya.jpg/960px-Royal_Botanic_Gardens%2C_Peradeniya.jpg",
    },
    {
        "kind": "attraction",
        "name": "Coconut Tree Hill",
        "used_for": "Mirissa / Coconut Tree Hill",
        "title": "File:View from Coconut Tree Hill to Mirissa in March.jpg",
        "author": "Alexey Komarov",
        "license": "CC BY-SA 4.0",
        "license_url": "https://creativecommons.org/licenses/by-sa/4.0",
        "source": "https://commons.wikimedia.org/wiki/File:View_from_Coconut_Tree_Hill_to_Mirissa_in_March.jpg",
        "url": "https://upload.wikimedia.org/wikipedia/commons/thumb/8/8b/View_from_Coconut_Tree_Hill_to_Mirissa_in_March.jpg/960px-View_from_Coconut_Tree_Hill_to_Mirissa_in_March.jpg",
    },
    {
        "kind": "attraction",
        "name": "Mirissa Beach",
        "used_for": "Mirissa / Mirissa Beach",
        "title": "File:Mirissa beach, Srilanka.jpg",
        "author": "Abishek Palraj",
        "license": "CC BY-SA 4.0",
        "license_url": "https://creativecommons.org/licenses/by-sa/4.0",
        "source": "https://commons.wikimedia.org/wiki/File:Mirissa_beach,_Srilanka.jpg",
        "url": "https://upload.wikimedia.org/wikipedia/commons/thumb/6/6f/Mirissa_beach%2C_Srilanka.jpg/960px-Mirissa_beach%2C_Srilanka.jpg",
    },
    {
        "kind": "attraction",
        "name": "Mirissa Whale Watching Tour",
        "used_for": "Mirissa / Mirissa Whale Watching Tour",
        "title": "File:Mirissa, whale watching, blue whale (6918166357).jpg",
        "author": "Arian Zwegers",
        "license": "CC BY 2.0",
        "license_url": "https://creativecommons.org/licenses/by/2.0",
        "source": "https://commons.wikimedia.org/wiki/File:Mirissa,_whale_watching,_blue_whale_(6918166357).jpg",
        "url": "https://upload.wikimedia.org/wikipedia/commons/thumb/d/d1/Mirissa%2C_whale_watching%2C_blue_whale_%286918166357%29.jpg/960px-Mirissa%2C_whale_watching%2C_blue_whale_%286918166357%29.jpg",
    },
    {
        "kind": "attraction",
        "name": "Negombo Beach",
        "used_for": "Negombo / Negombo Beach",
        "title": "File:Negombo Beach, Sri Lanka.jpg",
        "author": "S B from Sydney, Australia",
        "license": "CC BY 2.0",
        "license_url": "https://creativecommons.org/licenses/by/2.0",
        "source": "https://commons.wikimedia.org/wiki/File:Negombo_Beach,_Sri_Lanka.jpg",
        "url": "https://upload.wikimedia.org/wikipedia/commons/thumb/9/97/Negombo_Beach%2C_Sri_Lanka.jpg/960px-Negombo_Beach%2C_Sri_Lanka.jpg",
    },
    {
        "kind": "attraction",
        "name": "Negombo Lagoon Boat Tour",
        "used_for": "Negombo / Negombo Lagoon Boat Tour",
        "title": "File:Boats Anchored in Negambo Lagoon.jpg",
        "author": "Deshan Ruhunage",
        "license": "CC BY-SA 4.0",
        "license_url": "https://creativecommons.org/licenses/by-sa/4.0",
        "source": "https://commons.wikimedia.org/wiki/File:Boats_Anchored_in_Negambo_Lagoon.jpg",
        "url": "https://upload.wikimedia.org/wikipedia/commons/thumb/9/94/Boats_Anchored_in_Negambo_Lagoon.jpg/960px-Boats_Anchored_in_Negambo_Lagoon.jpg",
    },
    {
        "kind": "attraction",
        "name": "Saint Mary's Church Negombo",
        "used_for": "Negombo / Saint Mary's Church Negombo",
        "title": "File:St. Mary's Church, Negombo in 2024.jpg",
        "author": "MKoala",
        "license": "CC BY-SA 4.0",
        "license_url": "https://creativecommons.org/licenses/by-sa/4.0",
        "source": "https://commons.wikimedia.org/wiki/File:St._Mary%27s_Church,_Negombo_in_2024.jpg",
        "url": "https://upload.wikimedia.org/wikipedia/commons/thumb/7/79/St._Mary%27s_Church%2C_Negombo_in_2024.jpg/960px-St._Mary%27s_Church%2C_Negombo_in_2024.jpg",
    },
    {
        "kind": "attraction",
        "name": "Gregory Lake",
        "used_for": "Nuwara Eliya / Gregory Lake",
        "title": "File:Gregory Lake Nuwara Eliya 02.jpg",
        "author": "Kalana Jayatilake",
        "license": "CC BY-SA 4.0",
        "license_url": "https://creativecommons.org/licenses/by-sa/4.0",
        "source": "https://commons.wikimedia.org/wiki/File:Gregory_Lake_Nuwara_Eliya_02.jpg",
        "url": "https://upload.wikimedia.org/wikipedia/commons/thumb/7/7d/Gregory_Lake_Nuwara_Eliya_02.jpg/960px-Gregory_Lake_Nuwara_Eliya_02.jpg",
    },
    {
        "kind": "attraction",
        "name": "Hakgala Botanical Garden",
        "used_for": "Nuwara Eliya / Hakgala Botanical Garden",
        "title": "File:UG-LK Photowalk - 2018-03-25 - Hakgala Botanical Garden (1).jpg",
        "author": "Rehman Abubakr",
        "license": "CC BY-SA 4.0",
        "license_url": "https://creativecommons.org/licenses/by-sa/4.0",
        "source": "https://commons.wikimedia.org/wiki/File:UG-LK_Photowalk_-_2018-03-25_-_Hakgala_Botanical_Garden_(1).jpg",
        "url": "https://upload.wikimedia.org/wikipedia/commons/thumb/8/88/UG-LK_Photowalk_-_2018-03-25_-_Hakgala_Botanical_Garden_%281%29.jpg/960px-UG-LK_Photowalk_-_2018-03-25_-_Hakgala_Botanical_Garden_%281%29.jpg",
    },
    {
        "kind": "attraction",
        "name": "Horton Plains National Park",
        "used_for": "Nuwara Eliya / Horton Plains National Park",
        "title": "File:Horton Plains - World's end.jpg",
        "author": "JeninRathnayake",
        "license": "CC BY-SA 4.0",
        "license_url": "https://creativecommons.org/licenses/by-sa/4.0",
        "source": "https://commons.wikimedia.org/wiki/File:Horton_Plains_-_World%27s_end.jpg",
        "url": "https://upload.wikimedia.org/wikipedia/commons/thumb/b/b4/Horton_Plains_-_World%27s_end.jpg/960px-Horton_Plains_-_World%27s_end.jpg",
    },
    {
        "kind": "attraction",
        "name": "Gal Vihara",
        "used_for": "Polonnaruwa / Gal Vihara",
        "title": "File:Gal Vihara Polonnaruwa 1.jpg",
        "author": "Philip Nalangan",
        "license": "CC BY 4.0",
        "license_url": "https://creativecommons.org/licenses/by/4.0",
        "source": "https://commons.wikimedia.org/wiki/File:Gal_Vihara_Polonnaruwa_1.jpg",
        "url": "https://upload.wikimedia.org/wikipedia/commons/thumb/c/c4/Gal_Vihara_Polonnaruwa_1.jpg/960px-Gal_Vihara_Polonnaruwa_1.jpg",
    },
    {
        "kind": "attraction",
        "name": "Polonnaruwa Quadrangle",
        "used_for": "Polonnaruwa / Polonnaruwa Quadrangle",
        "title": "File:Polonnaruwa Vatadage Sri Lanka.jpg",
        "author": "Philip Nalangan",
        "license": "CC BY-SA 4.0",
        "license_url": "https://creativecommons.org/licenses/by-sa/4.0",
        "source": "https://commons.wikimedia.org/wiki/File:Polonnaruwa_Vatadage_Sri_Lanka.jpg",
        "url": "https://upload.wikimedia.org/wikipedia/commons/thumb/c/c7/Polonnaruwa_Vatadage_Sri_Lanka.jpg/960px-Polonnaruwa_Vatadage_Sri_Lanka.jpg",
    },
    {
        "kind": "attraction",
        "name": "Royal Palace of Parakramabahu",
        "used_for": "Polonnaruwa / Royal Palace of Parakramabahu",
        "title": "File:Royal Palace of King Parakramabahu, Ancient City of Polonnaruwa, Sri Lanka (2).jpg",
        "author": "Nahid Sultan",
        "license": "CC BY-SA 4.0",
        "license_url": "https://creativecommons.org/licenses/by-sa/4.0",
        "source": "https://commons.wikimedia.org/wiki/File:Royal_Palace_of_King_Parakramabahu,_Ancient_City_of_Polonnaruwa,_Sri_Lanka_(2).jpg",
        "url": "https://upload.wikimedia.org/wikipedia/commons/thumb/3/34/Royal_Palace_of_King_Parakramabahu%2C_Ancient_City_of_Polonnaruwa%2C_Sri_Lanka_%282%29.jpg/960px-Royal_Palace_of_King_Parakramabahu%2C_Ancient_City_of_Polonnaruwa%2C_Sri_Lanka_%282%29.jpg",
    },
    {
        "kind": "attraction",
        "name": "Minneriya National Park",
        "used_for": "Sigiriya / Minneriya National Park",
        "title": "File:Minneriya National Park, elephants gathering.jpg",
        "author": "Walter Gehr",
        "license": "CC BY-SA 4.0",
        "license_url": "https://creativecommons.org/licenses/by-sa/4.0",
        "source": "https://commons.wikimedia.org/wiki/File:Minneriya_National_Park,_elephants_gathering.jpg",
        "url": "https://upload.wikimedia.org/wikipedia/commons/thumb/3/39/Minneriya_National_Park%2C_elephants_gathering.jpg/960px-Minneriya_National_Park%2C_elephants_gathering.jpg",
    },
    {
        "kind": "attraction",
        "name": "Pidurangala Rock",
        "used_for": "Sigiriya / Pidurangala Rock",
        "title": "File:Pidurangala Rock depuis Sigiriya (1).jpg",
        "author": "Ji-Elle",
        "license": "CC BY-SA 3.0",
        "license_url": "https://creativecommons.org/licenses/by-sa/3.0",
        "source": "https://commons.wikimedia.org/wiki/File:Pidurangala_Rock_depuis_Sigiriya_(1).jpg",
        "url": "https://upload.wikimedia.org/wikipedia/commons/thumb/f/f3/Pidurangala_Rock_depuis_Sigiriya_%281%29.jpg/960px-Pidurangala_Rock_depuis_Sigiriya_%281%29.jpg",
    },
    {
        "kind": "attraction",
        "name": "Sigiriya Rock Fortress",
        "used_for": "Sigiriya / Sigiriya Rock Fortress",
        "title": "File:Sigiriya Rock fortress.jpg",
        "author": "Chamixth",
        "license": "CC BY-SA 4.0",
        "license_url": "https://creativecommons.org/licenses/by-sa/4.0",
        "source": "https://commons.wikimedia.org/wiki/File:Sigiriya_Rock_fortress.jpg",
        "url": "https://upload.wikimedia.org/wikipedia/commons/thumb/5/51/Sigiriya_Rock_fortress.jpg/960px-Sigiriya_Rock_fortress.jpg",
    },
    {
        "kind": "attraction",
        "name": "Kataragama Devalaya",
        "used_for": "Tissamaharama / Kataragama Devalaya",
        "title": "File:Kataragama temple entrance.jpg",
        "author": "Adbar",
        "license": "CC BY-SA 3.0",
        "license_url": "https://creativecommons.org/licenses/by-sa/3.0",
        "source": "https://commons.wikimedia.org/wiki/File:Kataragama_temple_entrance.jpg",
        "url": "https://upload.wikimedia.org/wikipedia/commons/thumb/c/c5/Kataragama_temple_entrance.jpg/960px-Kataragama_temple_entrance.jpg",
    },
    {
        "kind": "attraction",
        "name": "Tissamaharama Raja Maha Vihara",
        "used_for": "Tissamaharama / Tissamaharama Raja Maha Vihara",
        "title": "File:Tissamaharama Dagoba, 0648.jpg",
        "author": "Michael Gunther",
        "license": "CC BY-SA 4.0",
        "license_url": "https://creativecommons.org/licenses/by-sa/4.0",
        "source": "https://commons.wikimedia.org/wiki/File:Tissamaharama_Dagoba,_0648.jpg",
        "url": "https://upload.wikimedia.org/wikipedia/commons/thumb/e/eb/Tissamaharama_Dagoba%2C_0648.jpg/960px-Tissamaharama_Dagoba%2C_0648.jpg",
    },
    {
        "kind": "attraction",
        "name": "Yala National Park",
        "used_for": "Tissamaharama / Yala National Park",
        "title": "File:Leopard at Yala National Park.jpg",
        "author": "Manelka Jayasundara",
        "license": "CC BY-SA 4.0",
        "license_url": "https://creativecommons.org/licenses/by-sa/4.0",
        "source": "https://commons.wikimedia.org/wiki/File:Leopard_at_Yala_National_Park.jpg",
        "url": "https://upload.wikimedia.org/wikipedia/commons/thumb/a/a7/Leopard_at_Yala_National_Park.jpg/960px-Leopard_at_Yala_National_Park.jpg",
    },
    {
        "kind": "attraction",
        "name": "Fort Frederick",
        "used_for": "Trincomalee / Fort Frederick",
        "title": "File:Fort Fredrick, entrance.JPG",
        "author": "AntanO",
        "license": "CC BY-SA 4.0",
        "license_url": "https://creativecommons.org/licenses/by-sa/4.0",
        "source": "https://commons.wikimedia.org/wiki/File:Fort_Fredrick,_entrance.JPG",
        "url": "https://upload.wikimedia.org/wikipedia/commons/thumb/5/56/Fort_Fredrick%2C_entrance.JPG/960px-Fort_Fredrick%2C_entrance.JPG",
    },
    {
        "kind": "attraction",
        "name": "Koneswaram Temple",
        "used_for": "Trincomalee / Koneswaram Temple",
        "title": "File:Koneswaram temple of Trincomalee 01.jpg",
        "author": "Dr.S.Rajivraja",
        "license": "CC BY-SA 4.0",
        "license_url": "https://creativecommons.org/licenses/by-sa/4.0",
        "source": "https://commons.wikimedia.org/wiki/File:Koneswaram_temple_of_Trincomalee_01.jpg",
        "url": "https://upload.wikimedia.org/wikipedia/commons/thumb/a/a4/Koneswaram_temple_of_Trincomalee_01.jpg/960px-Koneswaram_temple_of_Trincomalee_01.jpg",
    },
    {
        "kind": "attraction",
        "name": "Nilaveli Beach",
        "used_for": "Trincomalee / Nilaveli Beach",
        "title": "File:Nilaveli Beach (31254637808).jpg",
        "author": "David Stanley from Nanaimo, Canada",
        "license": "CC BY 2.0",
        "license_url": "https://creativecommons.org/licenses/by/2.0",
        "source": "https://commons.wikimedia.org/wiki/File:Nilaveli_Beach_(31254637808).jpg",
        "url": "https://upload.wikimedia.org/wikipedia/commons/thumb/2/28/Nilaveli_Beach_%2831254637808%29.jpg/960px-Nilaveli_Beach_%2831254637808%29.jpg",
    },
    {
        "kind": "generic",
        "name": "beach_event",
        "used_for": "Generic photo: beach event",
        "title": "File:People dancing on the beach at night, Gili Trawangan (island), Indonesia.jpg",
        "author": "Vyacheslav Argenberg",
        "license": "CC BY 4.0",
        "license_url": "https://creativecommons.org/licenses/by/4.0",
        "source": "https://commons.wikimedia.org/wiki/File:People_dancing_on_the_beach_at_night,_Gili_Trawangan_(island),_Indonesia.jpg",
        "url": "https://upload.wikimedia.org/wikipedia/commons/thumb/d/d5/People_dancing_on_the_beach_at_night%2C_Gili_Trawangan_%28island%29%2C_Indonesia.jpg/960px-People_dancing_on_the_beach_at_night%2C_Gili_Trawangan_%28island%29%2C_Indonesia.jpg",
    },
    {
        "kind": "generic",
        "name": "budget_room",
        "used_for": "Generic photo: budget room",
        "title": "File:Hostel Room Inside at UAiU.jpg",
        "author": "ManoBV16",
        "license": "CC0",
        "license_url": "http://creativecommons.org/publicdomain/zero/1.0/deed.en",
        "source": "https://commons.wikimedia.org/wiki/File:Hostel_Room_Inside_at_UAiU.jpg",
        "url": "https://upload.wikimedia.org/wikipedia/commons/thumb/b/bc/Hostel_Room_Inside_at_UAiU.jpg/960px-Hostel_Room_Inside_at_UAiU.jpg",
    },
    {
        "kind": "generic",
        "name": "cafe",
        "used_for": "Generic photo: cafe",
        "title": "File:2019 02 Awesome Coffee Shop in Korat.jpg",
        "author": "Takeaway",
        "license": "CC BY-SA 4.0",
        "license_url": "https://creativecommons.org/licenses/by-sa/4.0",
        "source": "https://commons.wikimedia.org/wiki/File:2019_02_Awesome_Coffee_Shop_in_Korat.jpg",
        "url": "https://upload.wikimedia.org/wikipedia/commons/thumb/3/3f/2019_02_Awesome_Coffee_Shop_in_Korat.jpg/960px-2019_02_Awesome_Coffee_Shop_in_Korat.jpg",
    },
    {
        "kind": "generic",
        "name": "festival",
        "used_for": "Generic photo: festival",
        "title": "File:Water Carrier Dancers.jpg",
        "author": "Iamironviper",
        "license": "CC BY-SA 4.0",
        "license_url": "https://creativecommons.org/licenses/by-sa/4.0",
        "source": "https://commons.wikimedia.org/wiki/File:Water_Carrier_Dancers.jpg",
        "url": "https://upload.wikimedia.org/wikipedia/commons/thumb/b/b3/Water_Carrier_Dancers.jpg/960px-Water_Carrier_Dancers.jpg",
    },
    {
        "kind": "generic",
        "name": "indian_curry",
        "used_for": "Generic photo: indian curry",
        "title": "File:Indian Thali 2024.jpg",
        "author": "03Ani03",
        "license": "CC BY-SA 4.0",
        "license_url": "https://creativecommons.org/licenses/by-sa/4.0",
        "source": "https://commons.wikimedia.org/wiki/File:Indian_Thali_2024.jpg",
        "url": "https://upload.wikimedia.org/wikipedia/commons/thumb/4/4d/Indian_Thali_2024.jpg/960px-Indian_Thali_2024.jpg",
    },
    {
        "kind": "generic",
        "name": "midrange_room",
        "used_for": "Generic photo: midrange room",
        "title": "File:Hotel room Sri Lanka Photo212.jpg",
        "author": "psychoslave",
        "license": "CC BY-SA 4.0",
        "license_url": "https://creativecommons.org/licenses/by-sa/4.0",
        "source": "https://commons.wikimedia.org/wiki/File:Hotel_room_Sri_Lanka_Photo212.jpg",
        "url": "https://upload.wikimedia.org/wikipedia/commons/thumb/c/ca/Hotel_room_Sri_Lanka_Photo212.jpg/960px-Hotel_room_Sri_Lanka_Photo212.jpg",
    },
    {
        "kind": "generic",
        "name": "noodles",
        "used_for": "Generic photo: noodles",
        "title": "File:Fried rice in Colombo, Sri Lanka - 20111003.jpg",
        "author": "Shamli071.",
        "license": "CC BY-SA 3.0",
        "license_url": "https://creativecommons.org/licenses/by-sa/3.0",
        "source": "https://commons.wikimedia.org/wiki/File:Fried_rice_in_Colombo,_Sri_Lanka_-_20111003.jpg",
        "url": "https://upload.wikimedia.org/wikipedia/commons/thumb/9/9e/Fried_rice_in_Colombo%2C_Sri_Lanka_-_20111003.jpg/960px-Fried_rice_in_Colombo%2C_Sri_Lanka_-_20111003.jpg",
    },
    {
        "kind": "generic",
        "name": "perahera",
        "used_for": "Generic photo: perahera",
        "title": "File:Elephants of Kandy Esala Perahera.jpg",
        "author": "Daniel Liabeuf",
        "license": "CC BY-SA 3.0",
        "license_url": "https://creativecommons.org/licenses/by-sa/3.0",
        "source": "https://commons.wikimedia.org/wiki/File:Elephants_of_Kandy_Esala_Perahera.jpg",
        "url": "https://upload.wikimedia.org/wikipedia/commons/thumb/f/f5/Elephants_of_Kandy_Esala_Perahera.jpg/960px-Elephants_of_Kandy_Esala_Perahera.jpg",
    },
    {
        "kind": "generic",
        "name": "resort_pool",
        "used_for": "Generic photo: resort pool",
        "title": "File:Hotel pool by the beach Sri Lanka.jpg",
        "author": "psychoslave",
        "license": "CC BY-SA 4.0",
        "license_url": "https://creativecommons.org/licenses/by-sa/4.0",
        "source": "https://commons.wikimedia.org/wiki/File:Hotel_pool_by_the_beach_Sri_Lanka.jpg",
        "url": "https://upload.wikimedia.org/wikipedia/commons/thumb/5/56/Hotel_pool_by_the_beach_Sri_Lanka.jpg/960px-Hotel_pool_by_the_beach_Sri_Lanka.jpg",
    },
    {
        "kind": "generic",
        "name": "rice_and_curry",
        "used_for": "Generic photo: rice and curry",
        "title": "File:SL-rice and curry.jpg",
        "author": "me",
        "license": "CC BY-SA 4.0",
        "license_url": "https://creativecommons.org/licenses/by-sa/4.0",
        "source": "https://commons.wikimedia.org/wiki/File:SL-rice_and_curry.jpg",
        "url": "https://upload.wikimedia.org/wikipedia/commons/thumb/8/86/SL-rice_and_curry.jpg/960px-SL-rice_and_curry.jpg",
    },
    {
        "kind": "generic",
        "name": "seafood",
        "used_for": "Generic photo: seafood",
        "title": "File:Platter of grilled seafood, Charco Azul, La Palma.jpg",
        "author": "Gerda Arendt",
        "license": "CC0",
        "license_url": "http://creativecommons.org/publicdomain/zero/1.0/deed.en",
        "source": "https://commons.wikimedia.org/wiki/File:Platter_of_grilled_seafood,_Charco_Azul,_La_Palma.jpg",
        "url": "https://upload.wikimedia.org/wikipedia/commons/thumb/5/51/Platter_of_grilled_seafood%2C_Charco_Azul%2C_La_Palma.jpg/960px-Platter_of_grilled_seafood%2C_Charco_Azul%2C_La_Palma.jpg",
    },
    {
        "kind": "generic",
        "name": "street_food",
        "used_for": "Generic photo: street food",
        "title": "File:Kottu Roti (mit Meeresfrüchten).jpg",
        "author": "Dankesie",
        "license": "CC BY-SA 4.0",
        "license_url": "https://creativecommons.org/licenses/by-sa/4.0",
        "source": "https://commons.wikimedia.org/wiki/File:Kottu_Roti_(mit_Meeresfr%C3%BCchten).jpg",
        "url": "https://upload.wikimedia.org/wikipedia/commons/thumb/f/fa/Kottu_Roti_%28mit_Meeresfr%C3%BCchten%29.jpg/960px-Kottu_Roti_%28mit_Meeresfr%C3%BCchten%29.jpg",
    },
]
