from app.core.seed_data._helpers import hours

DESTINATION = {
    "name": "Polonnaruwa",
    "description": "Medieval capital of Sri Lanka with well-preserved ruins, giant Buddha statues and a vast reservoir.",
    "country": "Sri Lanka",
    "region": "North Central Province",
    "latitude": 7.9403,
    "longitude": 81.0188,
    "is_active": True,
    "attractions": [
        {
            "name": "Polonnaruwa Quadrangle",
            "description": "Compact group of ancient shrines including the Vatadage and Hatadage.",
            "latitude": 7.9411,
            "longitude": 81.0013,
            "entry_fee": 25.00,
            "duration_hours": 2.5,
            "rating": 4.8,
            "opening_hours": hours("07:30-18:00"),
        },
        {
            "name": "Gal Vihara",
            "description": "Four huge Buddha figures carved into a granite rock face.",
            "latitude": 7.9681,
            "longitude": 81.0057,
            "entry_fee": 0.00,
            "duration_hours": 1.0,
            "rating": 4.9,
            "opening_hours": hours("07:30-18:00"),
        },
        {
            "name": "Royal Palace of Parakramabahu",
            "description": "Ruins of the seven-storey royal palace and council chamber.",
            "latitude": 7.938,
            "longitude": 81.001,
            "entry_fee": 0.00,
            "duration_hours": 1.5,
            "rating": 4.4,
            "opening_hours": hours("07:30-18:00"),
        },
        {
            "name": "Lankathilaka Image House",
            "description": "Towering brick image house with a headless standing Buddha.",
            "latitude": 7.964,
            "longitude": 81.004,
            "entry_fee": 0.00,
            "duration_hours": 1.0,
            "rating": 4.4,
            "opening_hours": hours("07:30-18:00"),
        },
        {
            "name": "Rankoth Vehera",
            "description": "Second-largest stupa in the ancient city, set in woodland.",
            "latitude": 7.957,
            "longitude": 81.005,
            "entry_fee": 0.00,
            "duration_hours": 1.0,
            "rating": 4.3,
            "opening_hours": hours("07:30-18:00"),
        },
        {
            "name": "Parakrama Samudra",
            "description": "Enormous ancient reservoir with lakeside walks and sunsets.",
            "latitude": 7.93,
            "longitude": 81.013,
            "entry_fee": 0.00,
            "duration_hours": 1.5,
            "rating": 4.5,
            "opening_hours": hours("06:00-19:00"),
        },
        {
            "name": "Polonnaruwa Archaeological Museum",
            "description": "Museum with bronzes, models and finds from the ancient city.",
            "latitude": 7.9396,
            "longitude": 81.0,
            "entry_fee": 5.00,
            "duration_hours": 1.5,
            "rating": 4.2,
            "opening_hours": hours("08:00-17:00"),
        },
        {
            "name": "Minneriya Elephant Gathering Safari",
            "description": "Jeep safari to watch wild elephants gather beside the tank.",
            "latitude": 8.03,
            "longitude": 80.899,
            "entry_fee": 30.00,
            "duration_hours": 3.0,
            "rating": 4.6,
            "opening_hours": hours("06:00-18:00"),
        },
        {
            "name": "Giritale Lake",
            "description": "Quiet lake with birdlife and lakeside viewpoints.",
            "latitude": 7.995,
            "longitude": 80.94,
            "entry_fee": 0.00,
            "duration_hours": 1.5,
            "rating": 4.2,
            "opening_hours": hours("06:00-18:00"),
        },
        {
            "name": "Medirigiriya Vatadage",
            "description": "Circular relic house with carved stone pillars in a remote setting.",
            "latitude": 8.13,
            "longitude": 81.025,
            "entry_fee": 5.00,
            "duration_hours": 1.5,
            "rating": 4.1,
            "opening_hours": hours("08:00-17:00"),
        },
    ],
    "hotels": [
        {
            "name": "Polonnaruwa Budget Lodge",
            "description": "Friendly guesthouse near the bus station.",
            "latitude": 7.942,
            "longitude": 81.015,
            "price_per_night": 35.00,
            "facilities": ["WiFi", "Breakfast", "Fan"],
            "rating": 4.0,
        },
        {
            "name": "Parakrama Lake Resort",
            "description": "Mid-range resort overlooking the reservoir.",
            "latitude": 7.935,
            "longitude": 81.01,
            "price_per_night": 95.00,
            "facilities": ["WiFi", "Pool", "Restaurant", "Breakfast"],
            "rating": 4.4,
        },
        {
            "name": "Ancient City Boutique Hotel",
            "description": "Boutique hotel with colonial-style rooms and a garden.",
            "latitude": 7.946,
            "longitude": 81.008,
            "price_per_night": 150.00,
            "facilities": ["WiFi", "Restaurant", "Garden", "Spa"],
            "rating": 4.6,
        },
    ],
    "restaurants": [
        {
            "name": "Polonnaruwa Curry Hut",
            "description": "Simple eatery serving rice and curry at lunchtime.",
            "latitude": 7.941,
            "longitude": 81.017,
            "cuisine_type": "Local Sri Lankan",
            "avg_meal_cost": 7.00,
            "rating": 4.4,
            "operating_hours": hours("07:30-16:30"),
        },
        {
            "name": "Lake View Restaurant",
            "description": "Open-air restaurant on the reservoir bund.",
            "latitude": 7.933,
            "longitude": 81.012,
            "cuisine_type": "Local Sri Lankan",
            "avg_meal_cost": 12.00,
            "rating": 4.3,
            "operating_hours": hours("11:00-22:00"),
        },
        {
            "name": "Royal Spice Kitchen",
            "description": "Indian curries and biryani.",
            "latitude": 7.944,
            "longitude": 81.02,
            "cuisine_type": "Indian",
            "avg_meal_cost": 11.00,
            "rating": 4.2,
            "operating_hours": hours("11:00-22:30"),
        },
        {
            "name": "Dragon Garden Polonnaruwa",
            "description": "Chinese dishes in a leafy garden setting.",
            "latitude": 7.939,
            "longitude": 81.021,
            "cuisine_type": "Chinese",
            "avg_meal_cost": 12.00,
            "rating": 4.0,
            "operating_hours": hours("11:30-22:00"),
        },
        {
            "name": "Ancient City Grill",
            "description": "Western grill with steaks, burgers and desserts.",
            "latitude": 7.945,
            "longitude": 81.013,
            "cuisine_type": "Western",
            "avg_meal_cost": 17.00,
            "rating": 4.3,
            "operating_hours": hours("12:00-23:00"),
        },
    ],
    "events": [
        {
            "name": "Polonnaruwa Heritage Night",
            "description": "Evening music and dance performance among the lit ruins.",
            "latitude": 7.943,
            "longitude": 81.01,
            "entry_fee": 12.00,
            "rating": 4.6,
            "days_ahead": 70,
            "duration_days": 1,
            "start_time": "18:00",
            "end_time": "21:30",
        },
        {
            "name": "Giritale Lake Festival",
            "description": "Day-long lakeside festival with boat races and local food stalls.",
            "latitude": 7.998,
            "longitude": 80.943,
            "entry_fee": 4.00,
            "rating": 4.2,
            "days_ahead": 150,
            "duration_days": 1,
            "start_time": "09:00",
            "end_time": "18:00",
        },
    ],
}
