from app.core.seed_data._helpers import hours

DESTINATION = {
    "name": "Sigiriya",
    "description": (
        "Home to the ancient Sigiriya rock fortress in the Cultural Triangle, "
        "close to Dambulla's cave temples and wildlife parks."
    ),
    "country": "Sri Lanka",
    "region": "Central Province",
    "latitude": 7.9570,
    "longitude": 80.7603,
    "is_active": True,
    "attractions": [
        {
            "name": "Sigiriya Rock Fortress",
            "description": "UNESCO-listed 5th-century rock citadel with frescoes, mirror wall and summit ruins.",
            "latitude": 7.9572,
            "longitude": 80.7598,
            "entry_fee": 30.00,
            "duration_hours": 3.0,
            "rating": 4.9,
            "opening_hours": hours("07:00-17:30"),
        },
        {
            "name": "Pidurangala Rock",
            "description": "Climb to a boulder-strewn summit with the best view of Sigiriya Rock.",
            "latitude": 7.9660,
            "longitude": 80.7520,
            "entry_fee": 5.00,
            "duration_hours": 2.5,
            "rating": 4.7,
            "opening_hours": hours("05:00-18:00"),
        },
        {
            "name": "Sigiriya Museum",
            "description": "Museum with models and finds explaining the history of the fortress.",
            "latitude": 7.9510,
            "longitude": 80.7590,
            "entry_fee": 5.00,
            "duration_hours": 1.0,
            "rating": 4.2,
            "opening_hours": hours("09:00-17:00"),
        },
        {
            "name": "Dambulla Cave Temple",
            "description": "Five cave shrines with painted ceilings and over a hundred Buddha statues.",
            "latitude": 7.8570,
            "longitude": 80.6490,
            "entry_fee": 10.00,
            "duration_hours": 2.0,
            "rating": 4.7,
            "opening_hours": hours("07:00-19:00"),
        },
        {
            "name": "Minneriya National Park",
            "description": "Jeep safari to see wild elephants gathering by the Minneriya tank.",
            "latitude": 8.0300,
            "longitude": 80.8990,
            "entry_fee": 30.00,
            "duration_hours": 3.0,
            "rating": 4.6,
            "opening_hours": hours("06:00-18:00"),
        },
        {
            "name": "Kaudulla National Park",
            "description": "Elephant-watching safari in a quieter park with seasonal herds.",
            "latitude": 8.1300,
            "longitude": 80.9000,
            "entry_fee": 30.00,
            "duration_hours": 3.0,
            "rating": 4.5,
            "opening_hours": hours("06:00-18:00"),
        },
        {
            "name": "Village Cooking and Bullock Cart Experience",
            "description": "Village visit with a bullock-cart ride, boat trip and a home-cooked lunch demonstration.",
            "latitude": 7.9400,
            "longitude": 80.7700,
            "entry_fee": 15.00,
            "duration_hours": 2.5,
            "rating": 4.5,
            "opening_hours": hours("08:00-17:00"),
        },
        {
            "name": "Dambulla Golden Temple",
            "description": "Giant golden Buddha statue and Buddhist museum at the foot of the caves.",
            "latitude": 7.8575,
            "longitude": 80.6495,
            "entry_fee": 0.00,
            "duration_hours": 1.0,
            "rating": 4.3,
            "opening_hours": hours("06:00-19:00"),
        },
        {
            "name": "Habarana Lake",
            "description": "Peaceful lake with birdlife, lakeside walks and sunset views.",
            "latitude": 8.0400,
            "longitude": 80.7500,
            "entry_fee": 0.00,
            "duration_hours": 1.5,
            "rating": 4.2,
            "opening_hours": hours("06:00-18:00"),
        },
        {
            "name": "Ibbankatuwa Megalithic Tombs",
            "description": "Ancient burial site dating back over two thousand years.",
            "latitude": 7.9050,
            "longitude": 80.6800,
            "entry_fee": 5.00,
            "duration_hours": 1.0,
            "rating": 4.0,
            "opening_hours": hours("08:00-17:00"),
        },
    ],
    "hotels": [
        {
            "name": "Sigiriya Jungle Lodge",
            "description": "Eco-style lodge in the jungle with a view of the rock.",
            "latitude": 7.9500,
            "longitude": 80.7550,
            "price_per_night": 55.00,
            "facilities": ["WiFi", "Breakfast", "Air Conditioning", "Garden"],
            "rating": 4.2,
        },
        {
            "name": "Lion Rock View Resort",
            "description": "Comfortable resort with a pool and rooms overlooking Sigiriya Rock.",
            "latitude": 7.9650,
            "longitude": 80.7650,
            "price_per_night": 130.00,
            "facilities": ["WiFi", "Pool", "Restaurant", "Breakfast", "Parking"],
            "rating": 4.5,
        },
        {
            "name": "Sigiriya Heritage Villas",
            "description": "Luxury villas with private plunge pools set among paddy fields.",
            "latitude": 7.9450,
            "longitude": 80.7700,
            "price_per_night": 210.00,
            "facilities": ["WiFi", "Pool", "Spa", "Fine Dining", "Concierge"],
            "rating": 4.8,
        },
    ],
    "restaurants": [
        {
            "name": "Sigiriya Rice and Curry Hut",
            "description": "Village-style rice and curry served on banana leaf, open for lunch.",
            "latitude": 7.9560,
            "longitude": 80.7620,
            "cuisine_type": "Local Sri Lankan",
            "avg_meal_cost": 9.00,
            "rating": 4.5,
            "operating_hours": hours("08:00-17:00"),
        },
        {
            "name": "Rock View Terrace",
            "description": "Open-air restaurant with a view of the rock and Sri Lankan buffet dinners.",
            "latitude": 7.9585,
            "longitude": 80.7640,
            "cuisine_type": "Local Sri Lankan",
            "avg_meal_cost": 15.00,
            "rating": 4.4,
            "operating_hours": hours("11:00-22:00"),
        },
        {
            "name": "Village Spice Kitchen",
            "description": "Indian and Sri Lankan curries cooked in clay pots.",
            "latitude": 7.9540,
            "longitude": 80.7580,
            "cuisine_type": "Indian",
            "avg_meal_cost": 12.00,
            "rating": 4.3,
            "operating_hours": hours("11:00-22:30"),
        },
        {
            "name": "Sigiriya Wok and Grill",
            "description": "Chinese stir-fries and grilled meats for hungry hikers.",
            "latitude": 7.9555,
            "longitude": 80.7560,
            "cuisine_type": "Chinese",
            "avg_meal_cost": 13.00,
            "rating": 4.1,
            "operating_hours": hours("11:30-22:00"),
        },
        {
            "name": "Jungle Bistro",
            "description": "Garden bistro serving pasta, salads and wood-fired grills.",
            "latitude": 7.9530,
            "longitude": 80.7610,
            "cuisine_type": "Western",
            "avg_meal_cost": 20.00,
            "rating": 4.4,
            "operating_hours": hours("12:00-23:00"),
        },
    ],
    "events": [
        {
            "name": "Sigiriya Rock Light and Music Night",
            "description": "Evening concert of traditional drumming and music below the lit rock.",
            "latitude": 7.9590,
            "longitude": 80.7580,
            "entry_fee": 20.00,
            "rating": 4.6,
            "days_ahead": 75,
            "duration_days": 1,
            "start_time": "18:00",
            "end_time": "21:30",
        },
        {
            "name": "Dambulla Cultural Arts Festival",
            "description": "Daytime festival of Kandyan dance, masks and crafts near Dambulla.",
            "latitude": 7.8700,
            "longitude": 80.6600,
            "entry_fee": 6.00,
            "rating": 4.3,
            "days_ahead": 160,
            "duration_days": 1,
            "start_time": "10:00",
            "end_time": "17:00",
        },
    ],
}
