from app.core.seed_data._helpers import hours

DESTINATION = {
    "name": "Tissamaharama",
    "description": "Gateway town to Yala and Bundala national parks, with ancient stupas and a large lake.",
    "country": "Sri Lanka",
    "region": "Southern Province",
    "latitude": 6.2833,
    "longitude": 81.2879,
    "is_active": True,
    "attractions": [
        {
            "name": "Yala National Park",
            "description": "Famous safari park with leopards, elephants and sloth bears.",
            "latitude": 6.34,
            "longitude": 81.43,
            "entry_fee": 30.00,
            "duration_hours": 3.0,
            "rating": 4.8,
            "opening_hours": hours("06:00-18:00"),
        },
        {
            "name": "Bundala National Park",
            "description": "Wetland park for flamingos and migratory birds.",
            "latitude": 6.2,
            "longitude": 81.23,
            "entry_fee": 20.00,
            "duration_hours": 3.0,
            "rating": 4.5,
            "opening_hours": hours("06:00-18:00"),
        },
        {
            "name": "Kirinda Beach Temple",
            "description": "Seaside temple on a rock overlooking the ocean.",
            "latitude": 6.235,
            "longitude": 81.34,
            "entry_fee": 0.00,
            "duration_hours": 1.5,
            "rating": 4.3,
            "opening_hours": hours("06:00-18:00"),
        },
        {
            "name": "Tissamaharama Lake",
            "description": "Ancient reservoir with birdlife and sunset walks.",
            "latitude": 6.279,
            "longitude": 81.293,
            "entry_fee": 0.00,
            "duration_hours": 1.5,
            "rating": 4.4,
            "opening_hours": hours("06:00-19:00"),
        },
        {
            "name": "Tissamaharama Raja Maha Vihara",
            "description": "Whitewashed stupa dating back to the 3rd century BC.",
            "latitude": 6.28,
            "longitude": 81.286,
            "entry_fee": 0.00,
            "duration_hours": 1.0,
            "rating": 4.4,
            "opening_hours": hours("05:00-20:00"),
        },
        {
            "name": "Yatala Vehera",
            "description": "Ancient stupa surrounded by quiet gardens.",
            "latitude": 6.268,
            "longitude": 81.272,
            "entry_fee": 0.00,
            "duration_hours": 1.0,
            "rating": 4.1,
            "opening_hours": hours("06:00-18:00"),
        },
        {
            "name": "Kataragama Devalaya",
            "description": "Sacred shrine revered by Buddhists, Hindus and Muslims.",
            "latitude": 6.413,
            "longitude": 81.333,
            "entry_fee": 0.00,
            "duration_hours": 1.5,
            "rating": 4.6,
            "opening_hours": hours("04:00-20:00"),
        },
        {
            "name": "Debarawewa Lake Birdwatching",
            "description": "Calm lake edge for spotting pelicans, painted storks and kingfishers.",
            "latitude": 6.299,
            "longitude": 81.265,
            "entry_fee": 0.00,
            "duration_hours": 1.5,
            "rating": 4.2,
            "opening_hours": hours("06:00-18:00"),
        },
        {
            "name": "Lunugamvehera National Park",
            "description": "Quiet park of scrub and lake where elephants gather.",
            "latitude": 6.362,
            "longitude": 81.2,
            "entry_fee": 20.00,
            "duration_hours": 3.0,
            "rating": 4.3,
            "opening_hours": hours("06:00-18:00"),
        },
        {
            "name": "Sithulpawwa Rock Temple",
            "description": "Ancient rock monastery with cave paintings.",
            "latitude": 6.348,
            "longitude": 81.39,
            "entry_fee": 3.00,
            "duration_hours": 1.5,
            "rating": 4.4,
            "opening_hours": hours("07:00-17:00"),
        },
    ],
    "hotels": [
        {
            "name": "Tissa Budget Guesthouse",
            "description": "Clean, basic rooms close to the lake and bus stand.",
            "latitude": 6.285,
            "longitude": 81.29,
            "price_per_night": 28.00,
            "facilities": ["WiFi", "Breakfast", "Fan"],
            "rating": 4.0,
        },
        {
            "name": "Safari Gateway Lodge",
            "description": "Mid-range lodge with a garden and early safari breakfasts.",
            "latitude": 6.276,
            "longitude": 81.292,
            "price_per_night": 85.00,
            "facilities": ["WiFi", "Restaurant", "Breakfast", "Parking"],
            "rating": 4.3,
        },
        {
            "name": "Yala Edge Eco Resort",
            "description": "Luxury eco resort near the park with pool and spa.",
            "latitude": 6.31,
            "longitude": 81.33,
            "price_per_night": 170.00,
            "facilities": ["WiFi", "Pool", "Spa", "Restaurant"],
            "rating": 4.7,
        },
    ],
    "restaurants": [
        {
            "name": "Tissa Rice and Curry Shop",
            "description": "Local eatery serving rice and curry until early evening.",
            "latitude": 6.284,
            "longitude": 81.287,
            "cuisine_type": "Local Sri Lankan",
            "avg_meal_cost": 7.00,
            "rating": 4.4,
            "operating_hours": hours("07:00-16:30"),
        },
        {
            "name": "Lakeside Hopper House",
            "description": "Hoppers, string hoppers and Sri Lankan dinners by the lake.",
            "latitude": 6.28,
            "longitude": 81.291,
            "cuisine_type": "Local Sri Lankan",
            "avg_meal_cost": 10.00,
            "rating": 4.3,
            "operating_hours": hours("11:00-22:00"),
        },
        {
            "name": "Safari Spice Kitchen",
            "description": "Indian curries and biryani for hungry safari-goers.",
            "latitude": 6.282,
            "longitude": 81.289,
            "cuisine_type": "Indian",
            "avg_meal_cost": 11.00,
            "rating": 4.2,
            "operating_hours": hours("11:00-22:30"),
        },
        {
            "name": "Ruhuna Wok House",
            "description": "Chinese noodles, fried rice and devilled dishes.",
            "latitude": 6.286,
            "longitude": 81.285,
            "cuisine_type": "Chinese",
            "avg_meal_cost": 11.00,
            "rating": 4.0,
            "operating_hours": hours("11:30-22:00"),
        },
        {
            "name": "Yala Gate Grill",
            "description": "Western grill with burgers, steaks and pasta.",
            "latitude": 6.279,
            "longitude": 81.288,
            "cuisine_type": "Western",
            "avg_meal_cost": 16.00,
            "rating": 4.2,
            "operating_hours": hours("12:00-23:00"),
        },
    ],
    "events": [
        {
            "name": "Kataragama Esala Procession",
            "description": "Night-time pageant of dancers, drummers and decorated elephants.",
            "latitude": 6.412,
            "longitude": 81.334,
            "entry_fee": 0.00,
            "rating": 4.7,
            "days_ahead": 70,
            "duration_days": 1,
            "start_time": "18:00",
            "end_time": "22:00",
        },
        {
            "name": "Tissa Lake Wildlife Photo Fair",
            "description": "Daytime exhibition of wildlife photography with talks by guides and rangers.",
            "latitude": 6.281,
            "longitude": 81.294,
            "entry_fee": 4.00,
            "rating": 4.2,
            "days_ahead": 140,
            "duration_days": 1,
            "start_time": "10:00",
            "end_time": "17:00",
        },
    ],
}
