from app.core.seed_data._helpers import hours

DESTINATION = {
    "name": "Trincomalee",
    "description": "East-coast port city with beautiful beaches, a deep natural harbour, colonial forts and whale watching.",
    "country": "Sri Lanka",
    "region": "Eastern Province",
    "latitude": 8.5874,
    "longitude": 81.2152,
    "is_active": True,
    "attractions": [
        {
            "name": "Koneswaram Temple",
            "description": "Hilltop Hindu temple on Swami Rock with ocean views.",
            "latitude": 8.5826,
            "longitude": 81.238,
            "entry_fee": 0.00,
            "duration_hours": 1.5,
            "rating": 4.7,
            "opening_hours": hours("05:00-19:00"),
        },
        {
            "name": "Fort Frederick",
            "description": "Colonial fort with deer roaming the grounds.",
            "latitude": 8.575,
            "longitude": 81.229,
            "entry_fee": 0.00,
            "duration_hours": 1.5,
            "rating": 4.3,
            "opening_hours": hours("06:00-18:00"),
        },
        {
            "name": "Nilaveli Beach",
            "description": "Long white-sand beach with calm shallow water.",
            "latitude": 8.69,
            "longitude": 81.199,
            "entry_fee": 0.00,
            "duration_hours": 3.0,
            "rating": 4.7,
            "opening_hours": hours("06:00-18:00"),
        },
        {
            "name": "Pigeon Island National Park",
            "description": "Boat trip to a marine park with coral reefs, reef sharks and snorkelling.",
            "latitude": 8.724,
            "longitude": 81.207,
            "entry_fee": 20.00,
            "duration_hours": 3.0,
            "rating": 4.8,
            "opening_hours": hours("07:00-16:00"),
        },
        {
            "name": "Uppuveli Beach",
            "description": "Relaxed beach strip with cafes and good swimming.",
            "latitude": 8.608,
            "longitude": 81.226,
            "entry_fee": 0.00,
            "duration_hours": 3.0,
            "rating": 4.5,
            "opening_hours": hours("06:00-18:00"),
        },
        {
            "name": "Kanniya Hot Springs",
            "description": "Seven hot wells believed to have healing properties.",
            "latitude": 8.564,
            "longitude": 81.176,
            "entry_fee": 2.00,
            "duration_hours": 1.0,
            "rating": 4.0,
            "opening_hours": hours("07:00-18:00"),
        },
        {
            "name": "Marble Beach",
            "description": "Clear-water beach inside a military area with picnic spots.",
            "latitude": 8.538,
            "longitude": 81.25,
            "entry_fee": 3.00,
            "duration_hours": 3.0,
            "rating": 4.5,
            "opening_hours": hours("08:00-17:00"),
        },
        {
            "name": "Trincomalee Whale Watching Tour",
            "description": "Half-day boat trip to see blue and sperm whales.",
            "latitude": 8.57,
            "longitude": 81.233,
            "entry_fee": 40.00,
            "duration_hours": 4.0,
            "rating": 4.6,
            "opening_hours": hours("06:00-14:00"),
        },
        {
            "name": "Trincomalee War Cemetery",
            "description": "Well-kept Commonwealth cemetery in a peaceful garden.",
            "latitude": 8.557,
            "longitude": 81.22,
            "entry_fee": 0.00,
            "duration_hours": 1.0,
            "rating": 4.2,
            "opening_hours": hours("08:00-17:00"),
        },
        {
            "name": "Sober Island",
            "description": "Small island reached by boat, good for snorkelling and picnics.",
            "latitude": 8.625,
            "longitude": 81.256,
            "entry_fee": 10.00,
            "duration_hours": 2.0,
            "rating": 4.3,
            "opening_hours": hours("07:00-16:00"),
        },
    ],
    "hotels": [
        {
            "name": "Trinco Budget Stay",
            "description": "Simple rooms close to the bus stand and harbour.",
            "latitude": 8.59,
            "longitude": 81.218,
            "price_per_night": 38.00,
            "facilities": ["WiFi", "Breakfast", "Air Conditioning"],
            "rating": 4.0,
        },
        {
            "name": "Uppuveli Beach Hotel",
            "description": "Mid-range beachfront hotel with a pool.",
            "latitude": 8.605,
            "longitude": 81.224,
            "price_per_night": 100.00,
            "facilities": ["WiFi", "Pool", "Restaurant", "Breakfast"],
            "rating": 4.3,
        },
        {
            "name": "Nilaveli Palm Resort",
            "description": "Luxury beach resort with diving centre and spa.",
            "latitude": 8.685,
            "longitude": 81.2,
            "price_per_night": 175.00,
            "facilities": ["WiFi", "Pool", "Spa", "Restaurant", "Sea View"],
            "rating": 4.7,
        },
    ],
    "restaurants": [
        {
            "name": "Trinco Rice and Curry House",
            "description": "Local rice and curry served until late afternoon.",
            "latitude": 8.588,
            "longitude": 81.214,
            "cuisine_type": "Local Sri Lankan",
            "avg_meal_cost": 8.00,
            "rating": 4.4,
            "operating_hours": hours("07:30-16:30"),
        },
        {
            "name": "Harbour Seafood Grill",
            "description": "Evening seafood grill overlooking the harbour.",
            "latitude": 8.586,
            "longitude": 81.22,
            "cuisine_type": "Seafood",
            "avg_meal_cost": 24.00,
            "rating": 4.7,
            "operating_hours": hours("17:00-23:00"),
        },
        {
            "name": "Uppuveli Beach Cafe",
            "description": "Casual beach cafe with burgers, smoothies and pasta.",
            "latitude": 8.607,
            "longitude": 81.225,
            "cuisine_type": "Western",
            "avg_meal_cost": 14.00,
            "rating": 4.3,
            "operating_hours": hours("08:00-22:00"),
        },
        {
            "name": "Dutch Bay Indian Kitchen",
            "description": "South Indian curries, dosas and vegetarian dishes.",
            "latitude": 8.589,
            "longitude": 81.216,
            "cuisine_type": "Indian",
            "avg_meal_cost": 10.00,
            "rating": 4.2,
            "operating_hours": hours("11:00-22:30"),
        },
        {
            "name": "Lotus Chinese Restaurant",
            "description": "Chinese restaurant with seafood fried rice and noodles.",
            "latitude": 8.591,
            "longitude": 81.213,
            "cuisine_type": "Chinese",
            "avg_meal_cost": 12.00,
            "rating": 4.1,
            "operating_hours": hours("11:30-22:00"),
        },
    ],
    "events": [
        {
            "name": "Koneswaram Temple Festival",
            "description": "Annual temple festival with processions, drumming and street food.",
            "latitude": 8.584,
            "longitude": 81.237,
            "entry_fee": 0.00,
            "rating": 4.5,
            "days_ahead": 80,
            "duration_days": 1,
            "start_time": "16:00",
            "end_time": "22:00",
        },
        {
            "name": "Nilaveli Beach Festival",
            "description": "Beach festival of water sports, food stalls and live music.",
            "latitude": 8.688,
            "longitude": 81.201,
            "entry_fee": 8.00,
            "rating": 4.4,
            "days_ahead": 145,
            "duration_days": 1,
            "start_time": "10:00",
            "end_time": "20:00",
        },
    ],
}
